### ISSUE TITLE
Not compatible with Ethiopia update?

### ISSUE THREAD

**Issue by gunnergoz** [civfanatics/CQUI_Community-Edition#102]
**Describe the bug**
Does not seem to work with game once Ethiopia update is installed. City menu is the regular Civ VI menu.
**To Reproduce**

**Expected behavior**

**Screenshots**

**General informations**
 - Version [e.g. 1.0.0.256]
 - Expansion [e.g. None, Rise and Fall]
 - Other mods [e.g. YnAMP]

**Save game and logs**
Please attach if you can your save game and the logs. You can find them in `..\documents\my games\sid meier's civilization vi\` on windows or `/Users/[user]/Library/Application Support/Sid Meier's Civilization VI/` on Mac OS.

**Additional context**

**Comment by Infixo** [comment]
Please post logs.
Everything working good for me (surprisingly).

**Comment by Infixo** [comment]
The icons in the production menu look a bit weird. Looks like Firaxis changed something here.

**Comment by alimulhuda** [comment]
Not enough information to reproduce. The pull request #105 should fix all things we found to be broken with the Ethiopia update. Any issue that exists after the pull should have a new issue opened.
