### ISSUE TITLE
Patch 1.0.3.31 issues

### ISSUE THREAD

**Issue by Infixo** [civfanatics/CQUI_Community-Edition#103]
1. NotificationPanel throws an error in the log.

There was a change in the mechanics here. Firaxis uses wildcard include.
-- This wildcard include will include all loaded files beginning with "NotificationPanel_"
-- This method replaces the uses of include("NotificationPanel") in files that want to override 
-- functions from this file. If you're implementing a new "NotificationPanel_" file DO NOT include this file.
include("NotificationPanel_", true);

There is no need for _basegame, _xp1 and _xp2 files. Also no need to use ReplaceUIScript in the .modinfo.

2. Weird icons in the production panel.

Firaxis changed the textures and the way icons are displayed. There is 1 icon in .xml instead of 4 previously and some changes in .lua.

**Comment by SmithsonianDSP** [comment]
To add on this, I noticed a couple of issues:

- The "Next Action" hotkey and UI button (in lower right-hand corner) is no longer functioning correctly for actions besides units needing orders. (Select Production, Claim Great Person, Select Pantheon/Beliefs, Send Envoys, etc.).

  * This _might_  not be occurring after starting a new game, but definitely happening when saving the game and coming back. Disabling CQUI and loading the game causes the next action button to work correctly. Enabling it and reloading it breaks it, again.


- It seems there is an intermediate window for Secret Societies when appointing/selecting a secret society advisor that isn't being displayed. (Not game-breaking.)

**Comment by Sharky444** [comment]
Next Action button not working happens also with new games, on a freshly installed Civ VI Gathering Storm with only CQUI active and no other mods.

**Comment by alimulhuda** [comment]
Just a few things I noticed while playing around with this. The wildcard include is case sensitive and also matches to any part of the filename so the one they have will match to abc_NotificationPanel_xyz.lua. Also it seems the load order of the files is arbitrary so in the unmodded game it looks like it loads NotificationPanel, then NotificationPanel_Expansion2, then NotificationPanel_Expansion1.

I'm not sure if anyone else had started working on it but I really wanted to play a game properly and ended up fixing things (at least I think did, midnight commits usually have issues for me)

**Comment by the-m4a** [comment]
d'oh - forgot about the patch dropping.  looking at this now as well.  Thanks for hopping on it @alimulhuda

**Comment by the-m4a** [comment]
So far it's good, I will approve this and update the workshop
it appears it doesn't matter on the order of exp1 and exp2; they both add different functions with the only overlap of function RegisterHandlers, and both call the base version of whatever it thinks is the base version of it...

**Comment by Sharky444** [comment]
Please don't forget to approve the pull request.
