### ISSUE TITLE
Early game stuck on tech selection

### ISSUE THREAD

**Issue by Sharky444** [civfanatics/CQUI_Community-Edition#104]
Win 10, Platinum Edition of the game with Gathering Storm, every other Mod disabled. I start a new custom game. Hit the next action button, settler is selected. A city is founded. Now the next action symbol is to select a technology to develop. I hit the next action hotkey, but nothing happens. If I click on the circle (with the blue tech symbol inside) in the right lower corner of the screen nothing happens. This button is not clickable. I can select my warrior manually and move him, but next action is again selection of tech to develop, and the game is stuck. If I select the tech manually in the left upper corner, then the game proceeds. With the Community User Interface mod disabled, reloading the same game, the circle is clickable and the game proceeds.

Tested it also on another PC with another steam account, and a fresh game installation of Civ VI Platinum edition (same as on first PC). Subscribed to this mod. Again stuck on tech selection,. Tested also the by downloading the mod from github, with the same result.

**Comment by SmithsonianDSP** [comment]
The "Next Action" button in the lower right-hand corner of the screen is currently broken for pretty much all actions except units needing orders. See my comment on #103. You have to open the tech window (and any other windows) manually using the toolbar in the upper left of the screen, right now.
