### ISSUE TITLE
cqui_settings_local.sql not working

### ISSUE THREAD

**Issue by Sharky444** [civfanatics/CQUI_Community-Edition#107]
The location of the cqui_settings_local.sql on my system:

e:\Steam\steamapps\workshop\content\289070\2115302648\Assets\

The file was there from the beginning, right after subscription.

I have commented out this line:

         ("CQUI_AlwaysOpenTechTrees", 1), -- Always opens the full tech trees

and saved the file.

When I start a new game and go to CQUI settings, popups section, Always open tech trees is disabled.

**Comment by the-m4a** [comment]
I think the file got updated yesterday with the push to the workshop, can you post the entirety of the file?
I didn't make any changes to the ModInfo file so it should load, so I'm thinking that there is an issue with the sql file itself

**Comment by Sharky444** [comment]
attached

[cqui_settings_local.zip](https://github.com/civfanatics/CQUI_Community-Edition/files/4975514/cqui_settings_local.zip)

**Comment by Sharky444** [comment]
I don't think it's a problem with the file, as all I did is changing 0 to 1 and removing -- from the line.

**Comment by the-m4a** [comment]
yep, repro'd this.  will look into it.

**Comment by the-m4a** [comment]
I screwed this up, sorry about that.

That last line should be:

("CQUI_DUMMY_SETTING_TO_END_THE_SETTINGS_LOCAL_FILE", 0);

(it was missing the , 0 in the parenthesis

**Comment by the-m4a** [comment]
@Sharky444 as you may have seen, the version now live in the Steam workshop is fixed.
