### ISSUE TITLE
Feature Request: Religion Lens - Deemphasize non-religious units / Emphasize religious units

### ISSUE THREAD

**Issue by SmithsonianDSP** [civfanatics/CQUI_Community-Edition#108]
**Is your feature request related to a problem? Please describe.**
When the Religion lens is active (e.g., while having a religious unit selected), it can be difficult to quickly/easily discern other religious units on the map. Part of this is due to having the city's religion map area colored (many of which do not have a high contrast against the red attack/in-range tile indicator or against the jersey colors of various civs), but is made worse when the area is busy with a number of non-religious units (military units, traders, builders, etc.). This can sometimes lead to having rival Missionaries/Apostles slipping through and spreading religion. 

**Describe the solution you'd like**
While the Religion lens is active, I think it would help if the unit icons of non-religious units were made more transparent, and potentially add additional emphasis to the icons for religious units (make the unit icons larger, or maybe add an extra colored border around them? Not sure what's most feasible, there). 

**Describe alternatives you've considered**
I'm not really sure what other things would be feasible, but I'm open to anything that makes it easier to _quickly_ spot other religious units in the area while cycling through units. Ideally, the solution would also be color-blind friendly. 

If it's not possible to alter the unit icon size/transparency/etc. via lenses, then maybe removing any tile color/overlay on tiles with religious units within a city would be the best alternative? (Coloring the tile the same as the unit's religion wouldn't help distinguish units that are in their own religion's territory, and applying a different color runs into the same contrast and color-blind-friendly issues with different religion colors.)  

**Additional context**
N/A

**Comment by the-m4a** [comment]
not sure why it didn't auto-show here, but added a PR for this #181

**Comment by the-m4a** [comment]
this was integrated
