### ISSUE TITLE
Settler auto-lense not working

### ISSUE THREAD

**Issue by Sharky444** [civfanatics/CQUI_Community-Edition#111]
This may not be a bug, but a removed feature.

For two years I have used an old version of CQUI together with the Rise and Fall expansion. In this version when I clicked on a settler unit it switched automatically to the settler lense. Now I have a new installation of Civ VI Gathering storm, and CQUI from the workshop. If I click on settlers no settler lense is activated. I've looked at options and don't see it there either. Was that feature removed from CQUI, and if so, why?

**Comment by alimulhuda** [comment]
The only time I've noticed it fail to switch to the settler lens is with the first settler. After the first city is founded the other settlers seem to display the lens automatically. Are you observing the same thing, or is it failing to switch the lens even for newer settlers?

**Comment by the-m4a** [comment]
I reproduced this as well - first settler in game doesn't show the lens automatically, but next one will, once that first city is founded.  Interesting..

**Comment by wayneb64** [comment]
I don't remember the first settler ever getting the lens. It doesn't really need it and I think it would detract from that first load which is why they disabled it from the beginning.

**Comment by the-m4a** [comment]
yeah, just confirmed that the unmodified game behavior is this way.  that first settler has no lens applied.
The Events.LensLayerOn trigger fires when selecting a scout, but not a settler until that first city is built

**Comment by Sharky444** [comment]
You are right, happens only with the first settler.
