### ISSUE TITLE
Consider: Use Firaxis's Gossip Dialogs

### ISSUE THREAD

**Issue by the-m4a** [civfanatics/CQUI_Community-Edition#118]
These:
![image](https://user-images.githubusercontent.com/8787640/88970364-260be680-d267-11ea-8a68-e1c21faf62d1.png)

instead of what we have now in the game (the centered message on the blue background)

We could probably continue to use the shortened gossip strings with the dialogs that are off-center on the screen

**Comment by Infixo** [comment]
How is this popup behaving when the yield banners are fully open? Does it move down automatically or does it overlap?
I am using my Better Leader Icon mod and my yield  banners are much smaller, so I am curious.

**Comment by the-m4a** [comment]
don't know offhand, but that's a good point.  There had to be an adjustment made with CQUI's banners a while back so those didnt' overlap

**Comment by therealcrow999** [comment]
I did a test and took screenshot. I am using Concise UI, but the banner expanding still function like vanilla:

[img]https://i.imgur.com/BvTxXFF.jpg[/img]
[img]https://i.imgur.com/DxypBze.jpg[/img]

**Comment by the-m4a** [comment]
I have been playing around with this.  I like the Gossip screens, but the tiny font and tiny box with the default status type is just rough.  I propose the change be at least to make the not-Gossip boxes more readable:

![image](https://user-images.githubusercontent.com/8787640/89843899-d662d000-db2e-11ea-9eb8-1b6448cba0fd.png)

Font and width of the box in "Default" status message box is the same as Gossip.

Also, the code to trim the gossip string also appears to be out of date because CQUI\Assets\Text\Gossip_Text.xml exists, so at least for the time being we have CQUI doing work it doesn't need to do.

Regarding the look, it'd be nice to make the box size configurable... however that's only possible if all of statusmessagepanel.lua is replaced, _and_ the presence of NovaGossipPanel.lua implies that statusmessagepanel.lua may not be around for much longer...

**Comment by Infixo** [comment]
Implemented in #140
