### ISSUE TITLE
Tech/Civic Tree and Civilopedia autofocus on the search bar

### ISSUE THREAD

**Issue by the-m4a** [civfanatics/CQUI_Community-Edition#119]
It seems we have a feature in our mod description that may no longer function:  (From SteamWorkshop thread)

* Tech/Civic Tree and Civilopedia now autofocus the searchbar

In tech and civic tree this works but not in civilopedia for me at least, meaning when i go in the civilopedia i have to click the search bar with the mouse manually instead of already being selected on opening the window. This seems veeer minor, but if you use it often it is sooo annoying and very uncomfortable.

**Comment by Infixo** [comment]
Civilopedia is no longer a part of CQUI.
Long time ago Pedia was in CQUI because there was a history and a back button. This functionality is in the base game, so probably was removed.
And the base version is missing AutoFocus.

**Comment by Infixo** [comment]
If you want to add it back then 1 line is missing in OnOpenCivilopedia():
	Controls.SearchEditBox:TakeFocus();

**Comment by chaorace** [comment]
I think we could get away with function replacement this time if that's all we plan to add to the Civilopedia interface.

**Comment by the-m4a** [comment]
Closing as this is fixed
