### ISSUE TITLE
meeting a civilization for the first time hangs the UI (old CQUI folder interference)

### ISSUE THREAD

**Issue by alexeyOnGitHub** [civfanatics/CQUI_Community-Edition#12]
started a new game (latest Civ 6 version). the UI hangs upon meeting a new civ.
![image](https://user-images.githubusercontent.com/239741/83479376-4547ec80-a44d-11ea-897a-b38e62ff9188.png)

**Comment by alexeyOnGitHub** [comment]
never mind - turns out I had an old version of CQUI still present on disk (manually copied it there a while back). once I removed it, the new CQUI version worked fine.
note - disabling the old CQUI release in "mods" menu was NOT enough. needed to delete the folder with manually installed CQUI.

**Comment by MateusBelo** [comment]
hi, the same thing happens to me, even after i remove the old version

**Comment by alimulhuda** [comment]
@MateusBelo Try to disable all mods other than CQUI. Make sure there is only one version of CQUI being used. If you have done all this then follow the steps below
1. Quit Civilization 6 if it is running
2. Start Civilization 6
3. Start a new game and play until you get the issue
4. Save game if possible and quit Civilization 6
5. Attach the Lua.log file here (The file should be in "\Documents\My Games\Sid Meier's Civilization VI\Logs\Lua.log")

List the DLCs and Expansions you are using.
