### ISSUE TITLE
Repository Wiki?

### ISSUE THREAD

**Issue by the-m4a** [civfanatics/CQUI_Community-Edition#123]
@alexeyOnGitHub - Would you be able to add a Wiki?  We have collected a few nuggets of information that are floating around our issues right now and it'd be awesome to stash them in a wiki instead.

Wiki should be available under the settings for the repo.

Also, can you add @chaorace to the collection of folks with the same level access granted to the rest of us?  He's a CQUI guy that's been around for a while. :)

**Comment by alexeyOnGitHub** [comment]
hi! done - the Wiki section is now enabled for this repo.
I will send an invite to @chaorace

**Comment by the-m4a** [comment]
thanks!

**Comment by chaorace** [comment]
Awww man my cover is blown. Invite accepted, thanks for having me! :smiley:
