### ISSUE TITLE
Unit Upgrade Maintenance Cost

### ISSUE THREAD

**Issue by r3a1d3a1** [civfanatics/CQUI_Community-Edition#125]
**Is your feature request related to a problem? Please describe.**
It would be great to know the ongoing maintenance costs of a unit before upgrading it.

**Describe the solution you'd like**
To see the potential maintenance costs besides the required resources to upgrade a unit.

**Comment by Infixo** [comment]
See where exactly?

**Comment by r3a1d3a1** [comment]
In the tooltip when you hover over the upgrade button. Is it possible at all?

**Comment by Infixo** [comment]
Yes, it is possible.
I implemented similar functionality in Better Report Screen. When you wanna upgrade a unit then the tooltip shows besides the usual info also a resource base and maintenance costs.

**Comment by r3a1d3a1** [comment]
Kudos to you and the main devs for allowing such level of flexibility!

On a side note, despite probable infeasibility, it could be fantastic if partial upgrade of a unit was allowed, rather than only to the latest tech. It could surely help reduce maintenance costs, and potentially, if offered at a discount, the upfront cost of the upgrade as well.

**Comment by Infixo** [comment]
Completed.
