### ISSUE TITLE
Disable All

### ISSUE THREAD

**Issue by r3a1d3a1** [civfanatics/CQUI_Community-Edition#126]
**Is your feature request related to a problem? Please describe.**
I would like to enable only 2-3 features out of 100s offered by this mod.

**Describe the solution you'd like**
It would be great to have a single button that disables absolutely everything, so that then I can enable only a select few.

**Comment by Infixo** [comment]
There are options that allows you to customize some features. Please check them.
If you want more options - please specify what exactly you are missing.
Approach “make everything customizable”, imho is not feasible.

**Comment by r3a1d3a1** [comment]
So I basically want a minimalistic approach where after enabling the mod in "additional content" section, no changes are applied, until I enable a few select features in the settings page of the mod.

Tbh, my main problem is that I couldn't drag the screen using the left button anymore and tooltips would take forever to disappear. Not to mention the Lenses button that vanished into thin air :) I would like to only have this feature: "_Improved resource icons are dimmed to emphasize unutilized resources_" and nothing else!

Thank you very much btw!

**Comment by Infixo** [comment]
There is an .sql file that you can use locally to switch off and on desired functionalities.
However, there is no "minimal" version and imho there never will be.
Amount of work needed to implement such a hollistic approach will never justify the benefits.
So, use options and if there is no option you'd like to use then open a ticket here for that specific, singular option, and we can see it is worth implementing.

**Comment by Infixo** [comment]
> Tbh, my main problem is that I couldn't drag the screen using the left button anymore and tooltips would take forever to disappear. Not to mention the Lenses button that vanished into thin air :) 
> 
These look like some bugs, maybe open a ticket, describe what is happening, post logs, etc.

**Comment by alexeyOnGitHub** [comment]
can't comment on the technical feasibility on enabling CQUI features a-la-carte - I would trust Infixo on this, but one benefit IF we could do this would be to minimize the blast radius for each new Civ6 update. every time there is a new Civ update, we may have something broken (various reasons), and people may need to completely disable the plugin until all showstopper issues are fixed. 
if we could support a-la-carte on/off settings per each CQUI feature (or a set of features), that would make it easier for people to keep using the plugin, with just a couple things turned off - until they are fixed. 

it may be not worth the effort, given how the app is currently set up. but that would be the advantage as I see it.

**Comment by the-m4a** [comment]
For most of the Lua-based things, we could probably do that.  Anywhere that XML is heavily modified may create an issue.  That said... if we can continue to make progress on the "extend, not replace", we should (in theory) see less breaking changes whenever Civ6 is updated.

**Comment by the-m4a** [comment]
CQUI_Settings_Local.sql can be used to disable many things, and can be stored in the mod parent folder which will prevent it from being overwritten when the mod is updated on the steam workshop.  Not much to do with this issue for now, so closing.
