### ISSUE TITLE
Show Suzerain Icon in CityState Banner

### ISSUE THREAD

**Issue by the-m4a** [civfanatics/CQUI_Community-Edition#127]
This was another CQUI feature that I liked that disappeared sometime ago... there are artifacts of it currently in the code, though it was not completely functional, especially for the expansions.  I have the code ready for PR, but would rather seek opinions first 😃...

Few things:
1. Edit: figured this out, see post below.  ~What I _really_ want doesn't appear to be easily achieved: the Suzerain in the CS city banner is the icon of that civ, using that Civ's color scheme.~
  - ~For example, Japan would be the red flower backed by a white circle; Cree would have their symbol in green backed by the blue, etc.~
  - ~I could sort of achieve this with overlapping Icons (using the circle map pin as the one in the background color), but could not get the banners to size correctly.  Maybe more experimentation was in order.~
2. Edit: They'd both be using Container and Image objects defined in the XML. ~The different banner types for vanilla and the expansions means that, at least in my initial draft, there's two different ways these icons are added to the CS Banner:~
  - ~In vanilla, there is a container object with two images inside, defined in the XML~
  - ~In the expansions, I used the existing CityInfoStack, dynamically adding a button (in the same manner that the unlocked citizen "!" icon is added when that option is enabled).  This included setting the size of the icon/button (to 28,28) because it otherwise appeared too small, I thought.~
3. The original CQUI feature would use the leader icon in the CS banner.  I think I prefer the Civ icon, ~though in some cases it is not... great (Rome!)~ ... edit: once the size was corrected this looks okay, I think...

** see my more recent post... leaving this here for.. posterity reasons **
Various pictures for comparison and opinions:
![image](https://user-images.githubusercontent.com/8787640/89158251-ad38b300-d522-11ea-90db-47426b492447.png)

![image](https://user-images.githubusercontent.com/8787640/89158327-c5a8cd80-d522-11ea-857f-26a06858d9cd.png)

![image](https://user-images.githubusercontent.com/8787640/89158602-3b149e00-d523-11ea-855b-8be82cf1f942.png)

![image](https://user-images.githubusercontent.com/8787640/89158693-52ec2200-d523-11ea-8102-c17072f47265.png)

**Comment by the-m4a** [comment]
Approximation of what I'd like to see... it may be possible to do if not using the CityInfoStack, basically locate two buttons on top of one another.  ICON_MAP_PIN_CIRCLE is the one in the back, behind the Civ's icon.
![image](https://user-images.githubusercontent.com/8787640/89160089-5e404d00-d525-11ea-8c92-bb5b93376682.png)

**Comment by wayneb64** [comment]
Seeing the leaders faces on the banner doesn't seem natural to me. It's very noticeable but in a bad way.

**Comment by alexeyOnGitHub** [comment]
I wonder if it would make sense to start marking small features like this one as something people can switch on/off in the mod settings... some people may want these UI changes, while others may want to have fewer elements on the screen.
I think I would prefer more info shown, but not sure how other people will feel about this.

**Comment by the-m4a** [comment]
Yeah, I like the idea of all things configurable.  This is easy enough to do - the districts available is also in the same code path so both could be covered there.

**Comment by the-m4a** [comment]
I figured out how to do the icon with the background color the way I wanted.  Also set it up to be configurable (along with the districts available icon).  I need sleep, so I'll clean up the code tomorrow and send a PR at some point, assuming this looks ok to y'all...

As part of making the Districts Available icon configurable, I untethered it from the districts in the banner, so either or both could be enabled.

![image](https://user-images.githubusercontent.com/8787640/89274351-a75fd200-d5f5-11ea-9e54-71ffacd3f9e7.png)
No suzerain, then with Suzerain
![image](https://user-images.githubusercontent.com/8787640/89274498-d70eda00-d5f5-11ea-81ab-22c1f340cf4c.png)
![image](https://user-images.githubusercontent.com/8787640/89274571-f9085c80-d5f5-11ea-9f52-e0be15b93839.png)

![image](https://user-images.githubusercontent.com/8787640/89274625-0c1b2c80-d5f6-11ea-8796-f82cbcd65833.png)
![image](https://user-images.githubusercontent.com/8787640/89274674-19381b80-d5f6-11ea-98f2-5c81a9c41b10.png)
![image](https://user-images.githubusercontent.com/8787640/89275051-982d5400-d5f6-11ea-83fb-95072c26036a.png)

![image](https://user-images.githubusercontent.com/8787640/89275309-f65a3700-d5f6-11ea-9378-e8b4e765c586.png)
![image](https://user-images.githubusercontent.com/8787640/89275358-0b36ca80-d5f7-11ea-8dbe-d723a2a31514.png)

**Comment by alexeyOnGitHub** [comment]
I like this design
