### ISSUE TITLE
Great person panel, recruiting progress obscured

### ISSUE THREAD

**Issue by phielp** [civfanatics/CQUI_Community-Edition#129]
**Describe the bug**
When deciding to either recruit or pass a great person it is imposible to view the competitors progress.
![Schermopname (7)](https://user-images.githubusercontent.com/10925358/89437931-780daa00-d748-11ea-89db-fc9321d572c2.png)
Without the mod enabled it's accesible using the dropdown (triangle). 
![Schermopname (5)](https://user-images.githubusercontent.com/10925358/89437990-8956b680-d748-11ea-9947-89b886ed7f74.png)
![Schermopname (6)](https://user-images.githubusercontent.com/10925358/89438001-8cea3d80-d748-11ea-85fc-2bf5dc3b9c64.png)

**To Reproduce**
Open the great person panel, when eligible to recruit a great person.

**General informations**
 - OS: Windows 10
 - Version: 1.0.3.31
 - Expansion: GS and NFP
 - Other mods: Only CQUI through steam workshop (current version)

**Save game and logs**
[AutoSave_0074.zip](https://github.com/civfanatics/CQUI_Community-Edition/files/5029767/AutoSave_0074.zip)

**Comment by the-m4a** [comment]
Interesting... will take a look

**Comment by the-m4a** [comment]
Similar vein - when the Great Prophets are all dispensed, we shouldn't have this there

![image](https://user-images.githubusercontent.com/8787640/89507222-11f14900-d781-11ea-865a-7fa63edd325d.png)

**Comment by Infixo** [comment]
Fixed.
