### ISSUE TITLE
Lady six sky's name is missing on the trade report screen

### ISSUE THREAD

**Issue by christoph-kp** [civfanatics/CQUI_Community-Edition#13]
https://imgur.com/a/aR8rIT6

Shaka is there but she isn't.

**Comment by alexeyOnGitHub** [comment]
I can see "Lady Six Sky" text, but it uses a dark-green color font, which makes it pretty hard to read.

**Comment by christoph-kp** [comment]
You're right, if I squint I can just make it out. So this looks like it's an issue with the game, not the mod.
