### ISSUE TITLE
Diplomat (Governor) icon always shows on City State influence screen

### ISSUE THREAD

**Issue by the-m4a** [civfanatics/CQUI_Community-Edition#130]
As reported in the August issues thread.
This is not correct... I do not have this Governor assigned anywhere as of yet

![image](https://user-images.githubusercontent.com/8787640/89507071-de162380-d780-11ea-9ce3-f14736e8fd1a.png)

**Comment by the-m4a** [comment]
also suggested in that thread:
_Also, perhaps the opponent's Diplomats should face to the left, not to the right, to match how they're displayed on the main screen? Looks like the non-modded game flips the governors' icons on the vertical axis when displaying opponents' governors._

**Comment by Infixo** [comment]
Fixed.
