### ISSUE TITLE
Great person panel doesn't fit into 1366x768 screen

### ISSUE THREAD

**Issue by PriestSexist** [civfanatics/CQUI_Community-Edition#136]
**Describe the bug**
too close great person panel

**To Reproduce**
1. Start single player game on a map with 12 players, in secret societies game mode, with 4 level of Cataclysms (maybe there is some extra information)
2. open great person panel
3. See error
![ice_screenshot_20200809-022134](https://user-images.githubusercontent.com/69405678/89722155-dfe51e80-d9ee-11ea-9195-fef5b735e307.png)

**Comment by the-m4a** [comment]
is the error that all of the icons are Great Admirals?  Because if so, it at least confirms I'm not crazy, and it's fixed in a PR I am about to post

**Comment by PriestSexist** [comment]
yes, all of the icons are Great Admirals. It is one of the errors. But there is bigger error. When i open it (great person panel), it is too huge and it's impossible to hire some great persons

**Comment by the-m4a** [comment]
ah, okay, that second part is important information.  the screen you posted could've been cropped, wasn't sure.  I'll look at it (though I just merged the other changes :/ )

**Comment by the-m4a** [comment]
Ok well it's not the list - there's a scroll bar built in there, so now I'm curious if it's the resolution at which you're running, or if it's because it's in Russian?  The language shouldn't matter, so maybe it's screen resolution...

**Comment by Infixo** [comment]
The window has a minimum size to fit all elements, plus there are some fixed textures.
Maybe your resolution is too low - what is it?

**Comment by PriestSexist** [comment]
In previous versions everything was OK, so I don't think that it's problem with resolution. (My resolution is 1366x768)

**Comment by the-m4a** [comment]
alright, think I have something on this one.  I couldn't do 1366x768, but I could do 1024x768 so the overall effect should be the same since I'm only doing changes with the vertical heights

**Comment by the-m4a** [comment]
That panel itself, the layout and whatnot, is just a mess to deal with.  All the offsets and for whatever reason a Container object doesn't properly report it's SizeY.  I've been working on this one and trying to get it all to play nicely, trying to implement something less hacky that doesn't end up relying on lines that look like this:
```
 Controls.CQUI_RecruitWoodPaneling:SetSizeY(CQUI_preferedRecruitScrollSize + 32 + 28 + 48 + 20); 
```

**Comment by the-m4a** [comment]
Ok, simplified and think I got it.  Pasting this here for screen shots with the PR when I do that.
This is 1024x768 screen
![image](https://user-images.githubusercontent.com/8787640/90117199-707f6f80-dd0b-11ea-84fc-f25fb063c07a.png)

1920x1200 screen
![image](https://user-images.githubusercontent.com/8787640/90117698-1c28bf80-dd0c-11ea-9242-e482d528ff4c.png)

I can see there's a little bleed of that bottom woodpanel color, I'll adjust it before the PR.

**Comment by the-m4a** [comment]
Edit, not delete, grr...

Trying again.  Think I got it.  Will send a PR

1024x768:
![image](https://user-images.githubusercontent.com/8787640/90118387-023bac80-dd0d-11ea-8290-e6e951da911a.png)


1920x1200:
![image](https://user-images.githubusercontent.com/8787640/90118165-affa8b80-dd0c-11ea-9e19-792efc7fa19f.png)

**Comment by Infixo** [comment]
Fixed.
