### ISSUE TITLE
Make Right-click on pinlist operational

### ISSUE THREAD

**Issue by the-m4a** [civfanatics/CQUI_Community-Edition#148]
Per comment from Steam

The features list says "Right click in pinlist to quickly delete pins" but when I right click nothing happens. How do I enable this feature?

**Comment by Infixo** [comment]
Not working.

I think it was removed long time ago when Firaxis included Map Tacks into the game. All related files in CQUI were then removed because vanilla functionality was good.

**Comment by Infixo** [comment]
Lol This code is in the vanilla, just commented out
```

function OnMapPinFlagRightClick( playerID : number, pinID : number )
	-- TODO it might be nice to enable this if shift is down
	--[[
	-- If we are the owner of this pin, delete the pin.
	if(playerID == Game.GetLocalPlayer()) then
		local playerCfg = PlayerConfigurations[playerID];
		playerCfg:DeleteMapPin(pinID);
		Network.BroadcastPlayerInfo();
        UI.PlaySound("Map_Pin_Remove");
	end
	--]]
end
```

**Comment by the-m4a** [comment]
the joy of software development.  all the fun in creating new things, none of the fun in cleaning up, documenting, or taking care of those "todos".

**Comment by Infixo** [comment]
I will try to add this SHFT-down functionality. It makes sense to prevent from accidental removals.

**Comment by Infixo** [comment]
Done.
