### ISSUE TITLE
We likely do not need AffectsSavedGames = 1

### ISSUE THREAD

**Issue by the-m4a** [civfanatics/CQUI_Community-Edition#15]
Pointed out by infixo on the Steam msgs - as this is a UI mod, we should allow folks to turn it on and off.  Fix for this is just changing <AffectsSavedGames> to 0 in the .modinfo file.

**Comment by alexeyOnGitHub** [comment]
is there some state like build queue info, maybe trade sort info (last selected) , etc, that would be saved by the mod to disk?

**Comment by alexeyOnGitHub** [comment]
here is the commit message where the author set this flag to 1:

>  Added back AffectsSavedGames to save the settings  - The only uses for AffectsSavedGames is to save the user settings, so that you don't have when you load the game, to check back everything - You can disable the AffectsSavedGames is you want easily in the mod info file, it'll not break anything

**Comment by the-m4a** [comment]
Hmm... that seems a reasonable reason to have it, I wonder if it can be made configurable - isn’t there some sort of mod data cache?  (I remember in civ 5 there was a cache you had to clear when updating mods and the like...

**Comment by alexeyOnGitHub** [comment]
I would definitely prefer to have mod settings saved separately from the game itself. if those are settings are dropped / lost, the mod would just create a new default settings file without any consequence to the game save file. 

a UI mod should be optional and should not affect saved games, if at all possible.
