### ISSUE TITLE
Eureka turn reminder

### ISSUE THREAD

**Issue by Machine-Maker** [civfanatics/CQUI_Community-Edition#152]
**Is your feature request related to a problem? Please describe.**
No

**Describe the feature**
I seem to remember the original CQUI having a reminder to switch out policies if you were waiting to get the eureka to finish them off. I don't see this feature in the current version, hoping to get it back.

**Comment by Infixo** [comment]
Switch out policies? Eurekas have nothing to do with policies.
There is an information displayed on screen when a tech or civic reaches a point when it can be completed by boosting it. I.e. now it is 60%, 50% for China.

**Comment by Infixo** [comment]
Waiting for another confirmation whether this functionality works or not. Will close is in a couple of days in case there is no answer.

**Comment by wayneb64** [comment]
I seem to recall something on the next turn button prompting you to switch research if you had completed 60% and had not gotten the eureka yet, also one for unused city attacks.. The latter was converted to one of those status thingees just above the button but the former seems to have disappeared.

**Comment by Sorxus** [comment]
I can confirm that with both CQUI and Sukritact's Simple UI Adjustments notification about "The current ... is one turn away from maximum..." doesn't show up.
It works offcourse with CQUI only. 
Interesting, with Sukritact's Simple UI Adjustments doesn't show those notifications. It seems this mod causing it...
