### ISSUE TITLE
Issue list with August Update

### ISSUE THREAD

**Issue by the-m4a** [civfanatics/CQUI_Community-Edition#153]
List of issues observed thus far:
 - Not positive the 2nd place Suzerain is showing up... and so far that is the only thing I've seen in about 20 minutes of playing.  I'll look more later on this evening.

**Comment by alimulhuda** [comment]
Just updated the Civ6-UIFiles-Restructured repo. FYI in case it helps.

**Comment by Potworny** [comment]
The Population tab in the city view becomes blank sometime into the game (in some cases, when it was the last opened tab in the city view, the left part of the city view won't appear at all upon clicking on the city banner). Housing penalties either aren't calculated properly or they aren't displayed in the city view correctly (for example, the 50% penalty when housing is bigger by 1 than the population isn't noted in the UI). The changes made in the settings_local sql file don't apply in-game.

**Comment by the-m4a** [comment]
For at least the last one (settings) - the sql file would not apply to saved games, it maintains whatever was in the save.
Any chance you can share the save game of the other issue?

**Comment by Potworny** [comment]
The sql doesn't apply for me even on starting a new game. The problem with the city view starts happening after loading the game from a save. I'm not sure whether it's the same for housing calculation. In this save for example, Washington should have a 75% penalty (has 50%) and Boston should have 50%, but has 75%.

[USA.zip](https://github.com/civfanatics/CQUI_Community-Edition/files/5144539/USA.zip)

**Comment by Infixo** [comment]
@Potworny When did you start this usa game? Was before the patch or is a new one after the patch?

**Comment by Infixo** [comment]
@the-m4a I am checking out this USA game and 2nd place for City States is displayed properly.
However the issue I am seeing is that the number of envoys is incorrect for the 1st place when it is someone else. I.e. it shows 1 more than in the detailed panel "influenced by". I don't think it is related to the patch, could be an old issue not yet noticed.

**Comment by Infixo** [comment]
@Potworny 
Please open the game with CQUI disabled. Then it shows:
- Washington - 10 citizens, 11 housing => 50% slowed ok
- Boston - 7 citizen, 7 housing => 75% slowed ok
If the same values are shown with CQUI (and you claim so) then all is correct.
And btw, the above values are also shown in Better Report Screen, so I am pretty sure they are correct.

**Comment by Infixo** [comment]
The remaining issue is that the left screen (city overview) is not opening.

**Comment by wayneb64** [comment]
> @the-m4a I am checking out this USA game and 2nd place for City States is displayed properly.
> However the issue I am seeing is that the number of envoys is incorrect for the 1st place when it is someone else. I.e. it shows 1 more than in the detailed panel "influenced by". I don't think it is related to the patch, could be an old issue not yet noticed.

This is the way it has always worked for me, the number is actually the number required to be Suzerain.

**Comment by wayneb64** [comment]
I used to see the blank population tab issue all the time BEFORE you guys started working on CQUI, iow in the older CQUI. I have not seen it since using the new CQUI.

**Comment by Potworny** [comment]
This particular game was started on the current patch, however these issues appeared for me even before the update, consistently.
The housing issue doesn't seem to affect the actual gameplay, it just displays the available housing wrong in the city view. Washington has 11 available housing (as seen in the city status tab and in the game without CQUI), but in the city view, it shows 9, therefore the penalty seemed wrong to me. It's actually an issue with the display.
![image](https://user-images.githubusercontent.com/70391109/91636816-b757af80-ea03-11ea-9273-ae45ae133002.png)
![image](https://user-images.githubusercontent.com/70391109/91636820-c8082580-ea03-11ea-801e-09ca8538cac4.png)

**Comment by Infixo** [comment]
@Potworny Please make sure that you have the latest version of CQUI. I am seeing 10/11 in this panel.

**Comment by Infixo** [comment]
> This is the way it has always worked for me, the number is actually the number required to be Suzerain.
Lol, I didn't know that. Kind of assumed it showed number of envoys. So there is no issue with CS screen then.

**Comment by Potworny** [comment]
I have the most recent version of CQUI and the aforementioned issues do not appear without this mod.

**Comment by wayneb64** [comment]
Did you clear out any old versions in both of the places they can live?

**Comment by Potworny** [comment]
Yes, and reinstalling the mod and verifying the game's files brought no results.

**Comment by Infixo** [comment]
The issue with the Housing comes from this:
-- TEMP M4A TODO: This if/then below seems to alleviate the issue where CQUI_HousingFromImprovements is nil, but doesn't explain why it may have been nil to begin with
It returns nil in this case.

**Comment by Infixo** [comment]
@Potworny Check out #156

**Comment by Infixo** [comment]
@the-m4a 
I propose to finish PRs with citysupport, housing and icons and release it to Steam with the message that it is August patch compatible.

**Comment by Potworny** [comment]
Sorry if I'm a bit late, just woke up.
I've downloaded the latest master and the issue with the city banner and housing is gone, at least in the 'USA' save. My new games still don't react to the local settings files for some reason, but there's a major improvement anyway, thank you very much.

**Comment by Infixo** [comment]
New version with post-August changes is on Steam. Seems that issues mentioned in this thread have been addressed. Closing it.
