### ISSUE TITLE
Easily see when we are at war with a City State

### ISSUE THREAD

**Issue by Infixo** [civfanatics/CQUI_Community-Edition#157]
From Steam
Is there any way we could get a quick way to see which city states we're at war with without opening up the City States screen? Maybe putting the same red "crossed-sabers" war icon used on the leader ribbons on a corner of the city state's city banner?

**Comment by the-m4a** [comment]
oh, that's a good idea

**Comment by Infixo** [comment]
Implemented by @the-m4a in #174
