### ISSUE TITLE
CitySupport_CQUI files do not actually modify anything

### ISSUE THREAD

**Issue by the-m4a** [civfanatics/CQUI_Community-Edition#158]
CQUI has ReplaceUIScript for the CitySupport.lua file, with the intention of modifying the GetCityData function, by adding additional data to the data table returned.

As Infixo pointed out below, this file is meant to just be included, as it does not have it's own LuaContext and is shared by multiple files (diplomacydeal, citybannermanager, citypanel, citypaneloverview).

The fix will be to remove the "CitySupport_CQUI" files and modify the CQUI calls for GetCityData where that extra data returned is used.

**Edit**:  Seems the data retrieved by the extended GetCityData isn't ever directly used that I can find, so there's really no reason for these files at all.

**Comment by Infixo** [comment]
This file is to be used as include().
Please describe why you think “it doesn’t do anything”.

**Comment by the-m4a** [comment]
You said it - the file is meant to be included.  Whenever I made this change to try and do the ReplaceUIScript, it seemed to work, but apparently it does not.

I'll edit the initial post and clarify it.

**Comment by Infixo** [comment]
Include files are NOT supposed to be used in ReplaceUIScript. The only way to modify them is to overwrite them and just import to the game (ImportFiles section).

**Comment by the-m4a** [comment]
correct.  at the time of making those changes, I didn't know.  And I didn't see that immediately when first looking tonight.  Got it figured now.

**Comment by Infixo** [comment]
> CQUI has ReplaceUIScript for the CitySupport.lua file, with the intention of modifying the GetCityData function, by adding additional data to the data table returned.
> 

You can do it in 2 ways.
a) Create another function that adds data to the table and call it separately after GetCityData whenever needed.
b) Extend GetCityData the usual way, i.e. via calling BASE_xxx and then adding data. BUT you need to include a new file e.g. CitySupport_CQUI, not the original one. Original one gets included in CQUI's extension.

**Comment by the-m4a** [comment]
Right, it'd be "A" if that data was used anywhere.  

The CQUI GetCityData called the BASE_CQUI_GetCityData, and then added this to the object returned: 
```
    local productionInfo :table = GetCurrentProductionInfoOfCity( pCity, SIZE_PRODUCTION_ICON );
    data["ProductionProgress"] = productionInfo.Progress;
    data["ProductionCost"] = productionInfo.Cost;

    local pCityGrowth :table = pCity:GetGrowth();
    local foodSurplus :number = pCityGrowth:GetFoodSurplus();

    data.["CurrentFood"] =  pCityGrowth:GetFood();
    data.["RequiredFood"] = pCityGrowth:GetGrowthThreshold();
    data.["FoodGainNextTurn"] = foodSurplus * pCityGrowth:GetOverallGrowthModifier();
```
None of those values get used anywhere that I could find, a couple of them are calculated inline in the citypanel.lua (like RequiredFood).

**Comment by Infixo** [comment]
I confirm.
