### ISSUE TITLE
[Compatable Problem] Incompatable with CIVITAS City-States Expanded, breaking the city states panel

### ISSUE THREAD

**Issue by wzy9607** [civfanatics/CQUI_Community-Edition#16]
**Describe the bug**
As reported by Izzle in posts https://forums.civfanatics.com/threads/city-states-expanded.630256/page-6#post-15658014 and https://forums.civfanatics.com/threads/city-states-expanded.630256/page-6#post-15658157, when using both `CQUI` and `CIVITAS City-States Expanded` mod, the city state panel only shows one city state, and the send envoy button doesn't function.

**To Reproduce**
1. Enable `CQUI` and `CIVITAS City-States Expanded` mod.
2. Click on the city states button;

**Comment by alexeyOnGitHub** [comment]
I am not sure it is practically possible to maintain CQUI compatibility with multiple other plugins.
I believe the mod maintainers should focus on the **mod itself** and **its compatibility with the base game**.
as much as I would want to have peace in the world and all mods to play together nicely, 
attempting to support a combinatoric explosion of possible mods combinations would be cost-prohibitive. 

tagging @alimulhuda  and @the-m4a  - what is your opinion, guys?

**Comment by alimulhuda** [comment]
I agree that it is not going to be practical to maintain compatibility with everything. Right now I think we can look at requests like this on a case-by-case basis and if we have time see if we can sometimes at least offer some help.

In the case of this one, I'm not sure if we should do anything on CQUI to fix it. It appears there's two things that conflict between CQUI and CIVITAS. The city state screen and the trade route overview screen. It might be possible to fix things by changing the load in which the mod files get loaded. The CQUI will load those conflicting files after CIVITAS and this seems to be causing the issue. I don't think CQUI load order should be lowered enough for CIVITAS to work, but it is possible to increase the load order for CIVITAS to maybe fix things. I only quickly tried this out so there might be issues.

1. Edit CIVITAS City-States.modinfo (If installed via workshop it should be in C:\Program Files (x86)\Steam\steamapps\workshop\content\289070\1331757859)
2. Find the section that looks like the part below (the only difference should be the LoadOrder values) and modify LoadOrder to match the section below
```
    <ImportFiles id="CSE_Import">
      <Properties>
        <LoadOrder>250</LoadOrder>
      </Properties>
      <File>Core/Utilities/UI Replacements/CityStates.lua</File>
      <File>Core/Utilities/UI Replacements/CivilopediaPage_CityState.lua</File>
      <File>Core/Utilities/UI Replacements/CityStates.xml</File>
    </ImportFiles>
    <ReplaceUIScript id="CSE_CityStates_UI">
      <Properties>
        <LoadOrder>250</LoadOrder>
        <LuaContext>CityStates</LuaContext>
        <LuaReplace>Core/Utilities/UI Replacements/CityStates.lua</LuaReplace>
      </Properties>
    </ReplaceUIScript>
    <ReplaceUIScript id="CSE_TradeOverview_UI">
      <Properties>
        <LoadOrder>250</LoadOrder>
        <LuaContext>TradeOverview</LuaContext>
        <LuaReplace>Core/Utilities/UI Replacements/TradeOverview.lua</LuaReplace>
      </Properties>
    </ReplaceUIScript>
    <ImportFiles id="CSE_Import_Gov">
      <Properties>
        <LoadOrder>251</LoadOrder>
      </Properties>
      <Criteria>XP1</Criteria>
      <File>Core/Utilities/UI Replacements/XP1/CityStates_Expansion1.lua</File>
      <File>Core/Utilities/UI Replacements/XP1/CityStates.xml</File>
    </ImportFiles>
    <ReplaceUIScript id="CSE_CityStates_UI_Gov">
      <Properties>
        <LoadOrder>251</LoadOrder>
        <LuaContext>CityStates</LuaContext>
        <Criteria>XP1</Criteria>
        <LuaReplace>Core/Utilities/UI Replacements/XP1/CityStates_Expansion1.lua</LuaReplace>
      </Properties>
    </ReplaceUIScript>
```

I tried it with this change and I was not able to reproduce the issue mentioned. Personally I think that CQUI might be too big to accommodate changes like this. It might be better for the people having issues to contact CIVITAS and ask them if it's possible for the load order to be increased.

**Comment by wzy9607** [comment]
Thanks. It works for me, too. I'll try reach CIVITAS team to see if it's possible for them to increase load order.
