### ISSUE TITLE
Multiple reports of Settings_Local not doing things, investigate

### ISSUE THREAD

**Issue by the-m4a** [civfanatics/CQUI_Community-Edition#164]
Probably some weirdness with the fact that there's possibly two instances of this file now and if the latter is missing it just reverts all the things.  I am certain I tested that scenario and saw no issue, or at least _was_ certain, and now will look at it again.

**Comment by the-m4a** [comment]
I am not reproing this issue - at least in the expected scenario (where the cqui_settings_local.sql file is missing from the mod parent folder).

**Trial 1** (fresh start of Civ6, duel, vanilla):
- cqui_settings_local.sql is present in Mods\CQUI\Assets folder
  - "Always open full tree" is set to 1 
- cqui_settings_local.sql is not present in Mods folder
Modding.log snippet:
```
[1213788.596] Applying Component - CQUI_Settings_Local (UpdateDatabase)
[1213788.598] UpdateDatabase - Loading Assets/cqui_settings_local.sql
[1213788.599] Applying Component - CQUI_Settings_Local_ParentFolder (UpdateDatabase)
[1213788.601] UpdateDatabase - Loading ../cqui_settings_local.sql
[1213788.601] Warning: UpdateDatabase - Error Loading SQL.
```
Result: Loads correctly


Trial 2 - duel, vanilla:
- cqui_settings_local.sql is missing in Mods\CQUI\Assets folder
- cqui_settings_local.sql is present in Mods folder
  - CQUI_AutoapplyArchaeologistLens is 0  (defaults to 1)
Modding.log snippet:
```
[1214438.928] Applying Component - CQUI_Settings_Local (UpdateDatabase)
[1214438.930] UpdateDatabase - Loading Assets/cqui_settings_local.sql
[1214438.930] Warning: UpdateDatabase - Error Loading SQL.
[1214438.931] Applying Component - CQUI_Settings_Local_ParentFolder (UpdateDatabase)
[1214438.932] UpdateDatabase - Loading ../cqui_settings_local.sql
```
Result: Setting is applied correctly


Trial 3: Same as 2, except using Exp2 instead of vanilla
Result: Setting is applied correctly


...
So yeah, need more details from folks seeing this issue.

**Comment by Infixo** [comment]
Wait a minute. I thought that settings_local was MOVED to the parent folder, and now I see that it is loaded twice in .modinfo. Why is there still a load from ../Assets? I thought it was established that this file is deleted during Steam update, so what's the point keeping this entry in .modifo?

**Comment by Infixo** [comment]
Btw, I am using settings_local placed in the parent only and all seems to be working fine.

**Comment by the-m4a** [comment]
The intention was for backwards compatibility (call it a hard-to-shake behavior from my day job), but upon giving it more thought it's not necessary that it needs to exist in both places.  I'll create a PR to remove it.

**Comment by the-m4a** [comment]
We have 1 place for this file now, so closing this issue
