### ISSUE TITLE
Pike and Shot icon messed up in the build panel

### ISSUE THREAD

**Issue by wayneb64** [civfanatics/CQUI_Community-Edition#165]
Not sure if this is a Vanilla Civ issue or related to CQUI but I saw some very strange behavior yesterday, the Pike and Shot icons were either missing, broken or wrong and not even consistent. Adding three to the queue had a different icon for each.

![image](https://user-images.githubusercontent.com/35745304/91768073-b610b900-eba2-11ea-8815-89ce133aee29.png)

**Comment by Infixo** [comment]
Savefile?

**Comment by wayneb64** [comment]
[PikeAndShot.zip](https://github.com/civfanatics/CQUI_Community-Edition/files/5152842/PikeAndShot.zip)

**Comment by Infixo** [comment]
I don't think it is a problem with CQUI, rather there is something wrong with the icon. Here is how it looks in the BRS.

![obraz](https://user-images.githubusercontent.com/25866684/91896565-606b0800-ec99-11ea-88d9-03feff932892.png)

**Comment by wayneb64** [comment]
I posted this to the bug reports forum so maybe the devs can see/fix this.

**Comment by Infixo** [comment]
Probably should be closed after the next patch lands. Either will be fixed or not, but we can't fix it anyway in the latter case.
