### ISSUE TITLE
World Tracker research panel one turn behind

### ISSUE THREAD

**Issue by phielp** [civfanatics/CQUI_Community-Edition#168]
The research panel in the top left corner of the screen is one turn behind on the actual turn progress. Switching research also only updates on the next turn. If you go in to the research tree or select the panel it displays correctly. 

To reproduce: start a new game. I noticed it must be a recent update, I did not have the issue in my last game.

Tested it with and without CQUI as only mod.

![Schermopname (9)](https://user-images.githubusercontent.com/10925358/92000864-4e8f7080-ed3e-11ea-8463-b4b502a71668.png)
![Schermopname (10)](https://user-images.githubusercontent.com/10925358/92000874-518a6100-ed3e-11ea-88d3-c219ae9d98b4.png)

[researchPanel.zip](https://github.com/civfanatics/CQUI_Community-Edition/files/5163142/researchPanel.zip)

**Comment by Infixo** [comment]
If the problem exists also without CQUI then it is a base game issue and should be reported to Firaxis.
We may try to fix assuming it is UI-related.

**Comment by Infixo** [comment]
There is some issue with WT research panel not updating. It is CQUI related because it works correctly in the vanilla game. I am investigating it.

**Comment by phielp** [comment]
> Tested it with and without CQUI as only mod.

To clarify: I meant that I tried both setup (with and without mod enabled) but the problem indeed only occurs when CQUI is enabled.

**Comment by Infixo** [comment]
Fixed.
