### ISSUE TITLE
[Compatibility Issue] Incompatible with Extended Diplomacy Ribbon - Breaks Diplomacy Ribbon

### ISSUE THREAD

**Issue by Gigafrost** [civfanatics/CQUI_Community-Edition#17]
**Describe the bug**

When using both `CQUI `and `Extended Diplomacy Ribbon` mods, the Diplomacy Ribbon disappears, only showing your leader's icon.

**Without EDR mod:**
![](https://i.gyazo.com/1accbe750a4762f5f3d8a704eaf168a6.png)

**With EDR mod:**
![](https://i.gyazo.com/7cabd457223db9d62bdaca7cb5a28aab.png)

**To Reproduce**
1. Enable both `CQUI `and `Extended Diplomacy Ribbon` mods
2. Load into a game
3. Note the missing leader icons in the ribbon at the top of the screen.

Is there a way to make CQUI play nice with EDR? Or at least a way to disable CQUI's Diplomacy ribbon so I can use EDR's instead? Any help is appreciated.

**Comment by alimulhuda** [comment]
@Gigafrost Are you still interested in getting both of these mods working together? If yes let me know and there might be some things we can try but I will need your help with testing.

**Comment by Gigafrost** [comment]
> @Gigafrost Are you still interested in getting both of these mods working together? If yes let me know and there might be some things we can try but I will need your help with testing.

Yes I am, do let me know what i would need to do and I'd be happy to test it for you!

**Comment by paveldesigner** [comment]
Plaese, add this fix to base version of the mod. Or add the same functions to the CQUI =) It would be great!

**Comment by Gigafrost** [comment]
Thanks for letting me know all! I'll give a look and let you guys know how it goes in a bit.

**Comment by Gigafrost** [comment]
Back and just tested it. Not sure what you did but so far everything works beautifully!

![](https://i.gyazo.com/12a6166418a837a9452c06b5a3cbe908.jpg)

l'll post more about this if i find anything but i see no issues right now :)

**Comment by alimulhuda** [comment]
Okay, sounds good so far then. I'll try it in my games without EDR and see if I broke anything. If all looks good I'll request it be added to the main branch tomorrow. It might be longer until it gets pushed to the version on workshop, so until that happens you can continue using the version you are using.

All I did was add a check to CQUI to fallback to using the unmodded games function if it sees that something else modified the XML. It was a very small change so I'm hoping it didn't break anything.

**Comment by alimulhuda** [comment]
@the-m4a I'm going to put a pull request for this one in a few hours. If you are planning on doing another push to the workshop could you wait a little bit for this one as well.

**Comment by the-m4a** [comment]
Sounds good. I think if we are all in different files we won’t have too much issue. Git is decent with merges as well.  Awesome work!
