### ISSUE TITLE
More information on suzerainty + Leader Portraits instead of Civilization Icons in Suzerain Icon of Citystate Banner

### ISSUE THREAD

**Issue by Swarsele** [civfanatics/CQUI_Community-Edition#175]
What do you think about changing the current quick Suzerain implementation in CQUI to one that is closer to the one in "Suzerain at a Glance"?

![suz2](https://user-images.githubusercontent.com/32304731/92401076-3bf5ac80-f12d-11ea-8ecd-be7418a8336a.PNG)

Problem: Since only the civilization icon is shown, there is some ambiguity left on which leader is the actual suzerain (think Eleanor + Victoria when double civs are allowed).

Another feature that could be ported over is information on the exact amount of envoys sent by the current suzerain vs your own:

![suz1](https://user-images.githubusercontent.com/32304731/92401071-3b5d1600-f12d-11ea-83f7-2524af609028.PNG)
(red is your own envoys and only shown if you are not the current Suzerain - that functionality could also be expanded to also show the 2nd place civ)

As I see, there is currently a PR that already modifies the city state banner, so I figured I'd ask first how you would feel about such changes? Those should be able to be implemented pretty easily.

**Comment by Infixo** [comment]
Already discussed when implementing #127

**Comment by Swarsele** [comment]
Fair enough - but what about the idea of making it configurable between chosing civ icons or leader icons? As for myself, I do not have all the civ icons in my head, so they are not too useful to me. Also what about my second point - adding envoy numbers to the banner as shown in the second picture!

**Comment by Swarsele** [comment]
Maybe pictures explain it better than words:

I am suzerain:
![jjj1](https://user-images.githubusercontent.com/32304731/92412550-8c303700-f14c-11ea-82a9-ca7587b20f09.PNG)

I am not suzerain:
![qqq3](https://user-images.githubusercontent.com/32304731/92412556-92261800-f14c-11ea-8b21-e175b65644e4.PNG)

**Comment by the-m4a** [comment]
Making the thing configurable between leader pic and civ icon should be easy enough, if i remember correct it is only a couple of lines difference

**Comment by Swarsele** [comment]
I noticed there was a bug where the current suzerain would always be revealed even if not yet met by the player due to the check being made for if the citystate had already met the current suzerain, which is of course always the case.

I added a PR for the above suggestion and bugfix #184

**Comment by the-m4a** [comment]
this was completed
