### ISSUE TITLE
Add notification for a goody hut reward

### ISSUE THREAD

**Issue by Swarsele** [civfanatics/CQUI_Community-Edition#177]
**Describe the solution you'd like**
For example, if a goody hut gives 1 population, I would like to see a corresponding notification (see screenshot below). I do not understand why Firaxis has decided to only show the reward for a blink of a second upon picking up the goody hut, often times I miss it.

**Describe alternatives you've considered**
I tried to append the OnNotificationAdded function with 

```
if pNotification ~= nil and pNotification:GetTypeName() == "NOTIFICATION_DISCOVER_GOODY_HUT" then
			local eNum = GameInfo.Notifications[pNotification:GetTypeName()].Index;
			local target = pNotification:GetTarget();	
			local summary:string = Locale.Lookup(pNotification:GetSummary());
			local x, y = pNotification:GetLocation();
			LuaEvents.AddCustomNotification(pNotification:GetTypeName(), playerID, eNum, summary, x, y, target);
```
which seems to be what another mod was doing to achieve this, but it seems to not work so far. I fear I am not advanced enough to implement this myself.

**Additional context**
There was one mod that achieved this already - "Better visual notifications", however, the notifications are not the most beautiful (more of a civ 5 styl which does not fit too well here)
![cdcdc](https://user-images.githubusercontent.com/32304731/92414915-b850b580-f156-11ea-9fc4-13685173f2a6.PNG)

**Comment by Infixo** [comment]
NOTIFICATION_DISCOVER_GOODY_HUT - this notification is not active in the game core

**Comment by Infixo** [comment]
![obraz](https://user-images.githubusercontent.com/25866684/93026716-5d143c80-f608-11ea-99b3-9a9f4ce49ac7.png)
![obraz](https://user-images.githubusercontent.com/25866684/93026730-6ac9c200-f608-11ea-90ac-7e2de7de78a0.png)
![obraz](https://user-images.githubusercontent.com/25866684/93026736-74ebc080-f608-11ea-9297-2cbb0e1a2c31.png)
![obraz](https://user-images.githubusercontent.com/25866684/93026740-7e752880-f608-11ea-9743-57140bb7f6b4.png)

**Comment by Infixo** [comment]
The red color is now removed.

**Comment by Infixo** [comment]
Implemented.
