### ISSUE TITLE
HUD vanishing after meeting a new civ [from Steam]

### ISSUE THREAD

**Issue by Infixo** [civfanatics/CQUI_Community-Edition#179]
I'm having an issue with CQUI. The city names don't show and when I meet a new Civ it cause the entire hud to vanish. The only other mod oh have running is Enhanced Mod Manager. I have attached a save file with the issue.

Edit. Forgot to mention, playing on Steam.

[Bug Report Save.zip](https://github.com/civfanatics/CQUI_Community-Edition/files/5191197/Bug.Report.Save.zip)

_Originally posted by @Phillrbanks in https://github.com/civfanatics/CQUI_Community-Edition/issues/3#issuecomment-689148980_

**Comment by Infixo** [comment]
@phillrbanks
You are using an outdated version of the CQUI.
You savefile has CQUI attached to it. This feature was removed long time ago.

**Comment by Phillrbanks** [comment]
And I stand corrected, I ended up unsubscribing CQUI and restarted my game. I then re-subscribed and it worked.

**Comment by Infixo** [comment]
Ok, closing it.
