### ISSUE TITLE
Problem with Mayas'home (farms) and CQUI 

### ISSUE THREAD

**Issue by frostjerem** [civfanatics/CQUI_Community-Edition#18]
Hello, I discover today, when I build a farm with Maya'civilisation, the +1 home is not working, it gives only 0,5 home classical like other civs. 
I tried to play without CQUI in a new game, and the +1 home was back correctly with Mayas. 

Thanks for reading, and hope you can fix it !

**Comment by frostjerem** [comment]
@the-m4a @alimulhuda

**Comment by the-m4a** [comment]
PR is open for this one (with1 sign-off, needs 1 more).  I am uploading the change to Workshop right now

**Comment by frostjerem** [comment]
> PR is open for this one (with1 sign-off, needs 1 more). I am uploading the change to Workshop right now

**Comment by frostjerem** [comment]
Thank you very much for your good work !

**Comment by Dragonim** [comment]
Hello. Two Mayan farms give +3 housing (+2 ability and +1 for 2 farms) in the game without mods. With mods CQUI 2 farms give +2 housing.

Please fix this bug.

**Comment by the-m4a** [comment]
@Dragonim that bug is fixed in the current PR for the Seasteads housing reporting
the tool tip showing +1.5 housing for the Maya is also fixed in that PR

https://github.com/civfanatics/CQUI_Community-Edition/pull/49
