### ISSUE TITLE
Disable repeatable notifications

### ISSUE THREAD

**Issue by Infixo** [civfanatics/CQUI_Community-Edition#182]
There are few notifications that I find pretty annoying i.e. low amenities and low housing. I don't manage my cities by events, so I basically don't need them. They only take space and make noise.
I think it might be easy to disable them via SQL based on a setting in settings.sql.
Doing this via Lua would require (probably) plugging deep into UI code, which atm I don't wanna do.

**Comment by wayneb64** [comment]
I could certainly do without those two notifications.
