### ISSUE TITLE
Amenities calculation in CityScreen not correct

### ISSUE THREAD

**Issue by Swarsele** [civfanatics/CQUI_Community-Edition#188]
This has been a problem for a while - I posted this originally on the old repo, but it was never resolved.
When having built certain wonders (like Temple of Artemis) the amenities calculation will be off, both in the Panel as well as in the City Menu:

![errormenities](https://user-images.githubusercontent.com/32304731/93653818-d94cbc80-fa1a-11ea-87ae-1f27de3022c5.png)

Both the tooltips as well as the panel on the left fail to recognize the bonus amenities given by the temple. However, the end result in the CityOverviewPanel comes out to the right amount.

**Comment by Swarsele** [comment]
Possible fix: I am not sure how the extra amenities from stuff like ToA or Colosseum are handled internally, but maybe we can introduce a new category for that?

**Comment by Infixo** [comment]
All data is taken from the engine, most of it via CitySupport.lua

	data.AmenitiesFromLuxuries			= pCityGrowth:GetAmenitiesFromLuxuries();
	data.AmenitiesFromEntertainment		= pCityGrowth:GetAmenitiesFromEntertainment();
	data.AmenitiesFromCivics			= pCityGrowth:GetAmenitiesFromCivics();
	data.AmenitiesFromGreatPeople		= pCityGrowth:GetAmenitiesFromGreatPeople();
	data.AmenitiesFromCityStates		= pCityGrowth:GetAmenitiesFromCityStates();
	data.AmenitiesFromReligion			= pCityGrowth:GetAmenitiesFromReligion();
	data.AmenitiesFromNationalParks		= pCityGrowth:GetAmenitiesFromNationalParks();
	data.AmenitiesFromStartingEra		= pCityGrowth:GetAmenitiesFromStartingEra();
	data.AmenitiesFromImprovements		= pCityGrowth:GetAmenitiesFromImprovements();
	data.AmenitiesLostFromWarWeariness	= pCityGrowth:GetAmenitiesLostFromWarWeariness();
	data.AmenitiesLostFromBankruptcy	= pCityGrowth:GetAmenitiesLostFromBankruptcy();
	data.AmenitiesRequiredNum			= pCityGrowth:GetAmenitiesNeeded();
	data.AmenitiesFromDistricts			= pCityGrowth:GetAmenitiesFromDistricts();

You can check what happens with that and if anything is not missing.

**Comment by Infixo** [comment]
Btw, COL and TOA use different mechanisms. COL uses a simple value in the DB, and range. TOA uses a modifier.

**Comment by Infixo** [comment]
It seems that not all amenity sources where implemented in citypaneloverview.lua and citypanel.lua. I added missing: city-states, improvements, districts, natural wondes and traits.

![obraz](https://user-images.githubusercontent.com/25866684/100664778-65069180-3358-11eb-8bc8-edcf79f4b9fa.png)

**Comment by Infixo** [comment]
Fixed
