### ISSUE TITLE
Banners of City States and Other Civs are not clickable

### ISSUE THREAD

**Issue by the-m4a** [civfanatics/CQUI_Community-Edition#191]
Edited original post with more information and gifs demonstrating the behavior.  Like I said below, perhaps this was not something changed and I was just confusing the behavior of the player-owned cities with the City States and the other Civilizations:

CQUI Currently: Must click on the number icon to bring up the City State panel (or the "talk to other Civ").  Yellow dots appearing under the pointer in the gif is when I am left-clicking.
![gif](https://i.imgur.com/ZRsYPDT.gif)

Behavior Desired:  Click on the banner and the City State panel opens
![gif](https://i.imgur.com/BhtPcVj.gif)

I don't know yet if this is the fix, but the OnCityBannerClick RegisterCallBack in CQUI_Common_CityBanner_Initialize is only set when the following is satisfied:
```lua
    if (bannerType == BANNERTYPE_CITY_CENTER 
        and bannerStyle == BANNERSTYLE_LOCAL_TEAM 
        and playerID == Game.GetLocalPlayer()) then

        -- Register the callbacks 
        self.m_Instance.CityNameButton:RegisterCallback( Mouse.eMouseEnter, CQUI_OnBannerMouseOver );
        self.m_Instance.CityNameButton:RegisterCallback( Mouse.eMouseExit,  CQUI_OnBannerMouseExit );
        -- Re-register normal click as it gets hidden by a new button
        self.m_Instance.CityNameButton:RegisterCallback( Mouse.eLClick, OnCityBannerClick );
        self.m_Instance.CityNameButton:SetVoid1(playerID);
        self.m_Instance.CityNameButton:SetVoid2(cityID);
    end
```

Changing that if statement to simply this will at least produce the desired scenario (2nd gif).  I don't know yet if it has any other adverse effects, though, so didn't put together a PR.
```lua
    if (bannerType == BANNERTYPE_CITY_CENTER) then 
```

This issue is from a post made to the Steam Workshop:
```
Cuso 23 hours ago  
I am using the mod an I can't access the city state window or other civs diplomacy by clicking in the city banner. Both only works when clicking the number of population of the city. Is this a characteristic of the mod? Can it be reversed? or maybe there's some incompatibility?
```

**Comment by Infixo** [comment]
Instead of just what icon exactly? Banner is clickable, there is nothing to “restore”.

**Comment by the-m4a** [comment]
I perhaps mis-remembered that this was a change in behavior, or was confusing it with the banners of cities owned by the player.  Updated the title and top post with more info, as it's specifically the banners of the City States and other Civilizations that are not "clickable".

**Comment by the-m4a** [comment]
additionally: ScreenToGif is great and markdown supports formatting the lua code, three back-ticks ( ` character) with lua right after (like this):
```
```lua
```

**Comment by uhh186** [comment]
There is definitely a bug here. You can't bring up the City Details screen from clicking on the banner unless you click directly on the population, as you mentioned. Then, you will notice the City details screen that does pop up is bugged. You see variable names instead of the actual variables, and you can't edit the City Name either.

**Comment by uhh186** [comment]
@the-m4a There is definitely a bug here. You can't bring up the City Details screen from clicking on the banner unless you click directly on the population, as you mentioned. Then, you will notice the City details screen that does pop up is bugged. You see variable names instead of the actual variables, and you can't edit the City Name either.
