### ISSUE TITLE
strike buttons and encampent health bar gone

### ISSUE THREAD

**Issue by Khataro** [civfanatics/CQUI_Community-Edition#194]
encampment and city strike buttons missing since update yesterday. encampment health bars also missing. was working great until the latest update yesterday arrived, great mod btw!
edit: tested it without any other mod activated, only CQUI - Community Quick User Interface (Current Version)

**Comment by Khataro** [comment]
![20201023212855_1](https://user-images.githubusercontent.com/44543979/97045987-fa9f4c00-1576-11eb-8141-b00ea3fdaafe.jpg)

**Comment by Tfifa** [comment]
........./Mods/CQUI_Community-Edition-master/Assets/Expansion2/CityBanners/citybannerinstances.xml
                
                <Label ID="EncampmentFontIcon" Anchor="L,C" Offset="7,3" Style="FontNormal14" String="[Icon_DISTRICT_ENCAMPMENT]"/>

**Comment by Khataro** [comment]
I looked into the xml you posted, but i dont know how to fix the issue. Can you tell me what i have to change in the file to fallback to the vanilla buttons/bars? The problem is that i cant use the button to attack and dont realize there is an encampment at all. Everything else is working fine btw.

**Comment by wayneb64** [comment]
I am seeing this issue as well, breaks the game.

**Comment by Tfifa** [comment]
Line #255
   
                <Label ID="EncampmentFontIcon" Anchor="L,C" Offset="7,3" Style="FontNormal14" String="[Icon_DISTRICT_ENCAMPMENT]"/>

**Comment by Khataro** [comment]
I edited like this and it works again fine. Thanks for your help.
               
				<Label ID="EncampmentFontIcon" Anchor="L,C" Offset="7,3" Style="FontNormal14" String="[Icon_DISTRICT_ENCAMPMENT]"/>
                <Grid ID="DistrictDefenseGrid" Texture="Banner_StrengthBacking" Size="60,15" Anchor="C,T" AnchorSide="I,O" SliceTextureSize="42,15" SliceCorner="21,7" Color="255,255,255,150">

**Comment by wayneb64** [comment]
I don't see code like that at that line number in my local file, citybannerinstances.xml, which has a date of 09/26/2020, and you maybe attach the file?

My file was located at: 
D:\Steam\steamapps\workshop\content\289070\2115302648\Assets\Expansion2\CityBanners

**Comment by Khataro** [comment]
i pasted the line under "Distric strength"as the new line 256. I will upload my file so you can compare it.


[citybannerinstances.zip](https://github.com/civfanatics/CQUI_Community-Edition/files/5434793/citybannerinstances.zip)

**Comment by wayneb64** [comment]
Thanks, I figured it out, added the line like I said above. Hopefully the modders will get this file merged in so the next update won't undo this.

**Comment by the-m4a** [comment]
Sorry, have been mostly away and busy with things the past couple of weeks or so.  Uploaded the fix for this tonight to the Steam Workshop, will post a PR shortly.

**Comment by the-m4a** [comment]
Fixed with #196
