### ISSUE TITLE
Meteors / Fires may not spawn with CQUI running

### ISSUE THREAD

**Issue by the-m4a** [civfanatics/CQUI_Community-Edition#197]
This likely isn't a problem with CQUI per-se, but some sort of weird "Firaxis broke things and their fix happens to be a hack and CQUI is running into said hack" kind of thing.

Either way, there was at least 1 person mentioning it on the Steam site discussion, so if nothing else it's maybe something to look at.  The bug appeared with Ethopia, there is a fix contained in there that involves the database files introduced with Columbia/Maya:

https://forums.civfanatics.com/threads/1-0-3-31-no-meteor-shower-or-forest-fire-in-standard-or-ss-game.661216/

**Comment by Infixo** [comment]
Not CQUI related. A bug in the game installation, some issue with one of .modinfo files.
https://forums.civfanatics.com/threads/1-0-3-31-no-meteor-shower-or-forest-fire-in-standard-or-ss-game.661216/

**Comment by Infixo** [comment]
Fixed in the last patch. Closing it.
