### ISSUE TITLE
Combat log is overlapped by the top panel

### ISSUE THREAD

**Issue by the-m4a** [civfanatics/CQUI_Community-Edition#198]
From STeam discussion (Katy Carry):

Please help, I really enjoy this mod, but for some odd reason combat log is overlapped with top panel and is underneath it. All I see is the bottom frane of the combat log, kinda irritates. I use other UI mods like better report screen, better era score, better climate screen, and Sukricat UI mod.

**Comment by the-m4a** [comment]
I was looking at this and realized... I have no idea what "combat log" is, maybe when units fight with one another?  Anyone have an idea?

**Comment by alexeyOnGitHub** [comment]
right, that is the combat log. unit-fight-related messages flash and disappear quickly in the standard game UI, but there are mods that allow to see combat log in a scrollable panel. I haven't seen in the original game, so I think the author meant some 3rd party mod.
