### ISSUE TITLE
configure a script to release mod release and upload to Steam

### ISSUE THREAD

**Issue by alexeyOnGitHub** [civfanatics/CQUI_Community-Edition#20]
proposed requirements:
* no credentials saved in the script. the credentials (user/passw/api-key) should be accepted from command line params. these will be provided by Jenkins (CI tool running the builds).
* should run on a standard Linux VM with Python2/3 or bash, etc.
* should bump the mod version on each release build.
* should upload the distributive (set of files? zip archive?) to Steam, if the credentials are valid. should print an error message if the credentials are not provided
* I see a version number in "CQUI.modinfo" file. should this version be updated on each release? if yes, it should be a part of that script

once we have a script ready, I can:
* add it to a running Jenkins instance where it will be executed on each commit (merge) to master branch.

**Comment by alexeyOnGitHub** [comment]
@the-m4a @alimulhuda  hey guys, are you interested in working on this task?

**Comment by alexeyOnGitHub** [comment]
also, I see version number in "CQUI.modinfo" file. should this version be updated on each release? if yes, it should be a part of that script

**Comment by the-m4a** [comment]
is there any Rest API made available by steam that lets us publish outside of the Workshop uploader?  I assume there's something, but a quick search didn't provide me with hope beyond being able to query for stuff that already exists.

We're getting enough hits on the workshop msgs that we'll be busy with other things for a bit... :/

**Comment by stagnate** [comment]
Did a bit of research on this, and it looks like uploads to the workshop are controlled by each app (rather than directly by steam).  The application invokes the API calls to upload to the workshop, but the end-user needs to do it via the application.  Given that I don't expect that the upload process is going to be scriptable.

**Comment by DownTownScarf7** [comment]
This could be done by a Python3 script and [SteamCMD](https://developer.valvesoftware.com/wiki/SteamCMD#Linux), they even have a container, so you just need Python on that.

All this hinges on is if SteamCMD is what you are looking for and `subprocess` can in fact latch onto it. I've messed around with it a few times and once I uploaded a file to a game's steam workshop without any questions, so this seems perfect for automation to me.

Additional info for implementation, feel free to ignore, I just like to play around with ideas:

[argparse](https://docs.python.org/3/library/argparse.html) (builtin) can easily handle CLI arguments, implementation is simple.

```py
def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    
    parser.add_argument(
        '-u',
        '--username',
        default=os.environ['STEAM_USERNAME'],  # optional, for flexibility,  since Jenkins can set the environment too
        # this also provides and easy way to overwrite the credentials for specific uploads
        # however you if you throw this idea away, then you can set required=True, which instantly solves the checking for you
        help='The Steam username of the uploader',  # for clarity's sake
    )
    #  repeat add_argument for password and api key, additionally for version bumping, to decide between major and minor versions, there are many ways to do this, but here's one
    parser.add_argument(
        '-m',
        '--major',
        action='store_true',
        dest='is_major_version',
        help='Use if version change is major, omit if minor, used for version bumping',
    )

    return parser.parse_args()

# ignore try/except if required=True is set
try:
    args = parse_args()
except ValueError:
    print('Not all required arguments were set')
    sys.exit(1)
```

You can run SteamCMD via [subprocess.Popen](https://docs.python.org/3/library/subprocess.html#subprocess.Popen).

You can bump the version number with a builtin xml parser/handler of which Python has several or take an easier way out and use string templating.

I hope this helps, good luck!

**Comment by the-m4a** [comment]
closing as i don't think there's enough of a need with this one
