### ISSUE TITLE
Production panel not opening 

### ISSUE THREAD

**Issue by gare1987** [civfanatics/CQUI_Community-Edition#202]
**Describe the bug**
I extracted mod and enabled it, but it does not work properly.

**To Reproduce**

**Expected behavior**
Should it work ??

**Screenshots**

**General informations**
 - OS: WIN 10
 - Version CIV 1.0.0.328
 - Expansion Gathering Storm
 - Other mods; dont have any mods that affects UI, i tried it on default game maps.

**Save game and logs**

**Additional context**

**Comment by awebeer256** [comment]
Same here. Win10, game 1.0.0.341, all DLC I think.

I ran a bisect on the master branch: starting with 804d1c4a6a1e360e8789ba2055e650670f707cca, the production panel does not appear when you open the city view.

**Comment by wayneb64** [comment]
My game is working fine but my civ version is 1.0.6.9 (521158), do you not have Frontier Pass maybe?

**Comment by awebeer256** [comment]
Ok sorry I don't have Frontier Pass. I have Rise & Fall, Gathering Storm, Australia, Aztec, Khmer & Indonesia, Nubia, Persia & Macedon, Poland, Vikings, and a bunch of scenarios.

**Comment by Infixo** [comment]
New Frontier Pass contains also free updates. So, your game should be 1.0.6.9 atm.

**Comment by palexdev** [comment]
I have the same issue I will soon post logs or open a new issue because I think I have more than one problem
Also I'm on latest GS patch (should be 1.0.0.341), I have no intention to update till new content is completed
So the mod should be compatible with old versions too

**Comment by Infixo** [comment]
There are no "old versions" of the game. There is the current version and several DLCs that you can enable/disable. I can guranantee that now even Firaxis can make it so, that you might be able to run current DLCs on "older versions" of the game. Same is with the mods (actually any, not only CQUI). They should work with the current version and various configurations of DLCs (assuming they support the DLCs).
So, right now the mod works with the game version 1.0.8.x which is available for free for everyone who has the base game.

**Comment by palexdev** [comment]
Fine I'll stick with Concise UI then, after all I just wanted Improved Deal Screen from CQUI 🤷🏻

**Comment by Infixo** [comment]
> 
> 
> Fine I'll stick with Concise UI then, after all I just wanted Improved Deal Screen from CQUI 🤷🏻

Actually Deal Screen is much better in CUI imho :)

**Comment by gare1987** [comment]
> There are no "old versions" of the game - the game has one engine dedicated for base game, R&F and GS. On top of that engine you can enable/disable various DLCs. I can gurantee that now even Firaxis cannot make it so, that you could run current DLCs on "older versions" of the engine. Same is with the mods (actually any, not only CQUI). They should work with the current engine and various configurations of DLCs (assuming they support the DLCs).
> So, right now the mod works with the game version 1.0.8.x which is available for free for everyone who has the base game.
> 
> If you insist on using an older engine then you obviously need to download an older version of the mod.
No, it head the same problem even before Gathering storm, and i thought it was fixed with newerversin, but it still bugs.

**Comment by Infixo** [comment]
@gare1987 If the mod bugs now then please open a ticket. We try to make sure that the mod is updated after each patch and afaik it is working good atm. It is really hard to argue with the statement "it still bugs" without any details.

**Comment by gare1987** [comment]
If im not blind i posted it in issue category, so i already posted and stated what is the bug, i also wrote above that i thought it gonna work because its newer version and i thought it gonna be compatible with not latest version of the game. I was wrong, mod should be made compatible with older versions of the game or at least it should be posted separately to download for version that we need, there is no reason to not keep older versions of the mod.

**Comment by Infixo** [comment]
The mod works. The production panel is opening. You need to update your game.

**Comment by palexdev** [comment]
Meh this is just lazy, sorry but you are a lazy dev

**Comment by palexdev** [comment]
Oh wow now you delete my comments too? That's called censorship, seems like I touched the wrong spot, sorry for that :)
