### ISSUE TITLE
Production Menu Disappears and is no longer accessible once production is selected

### ISSUE THREAD

**Issue by TehGOOSE** [civfanatics/CQUI_Community-Edition#204]
**Describe the bug**
Once you select what you want to build the menu closes and you cannot access it again to queue or make changes till it finishes

**To Reproduce**
Launch game with todays patch, build city and select production.

**Screenshots**

**General informations**
 - Expansion : Gathering Storm w/ Latest New Frontier Pass (Babylon)
 - Other mods YnAMP

**Comment by drandarov-io** [comment]
Seems to only break when using the new Heroes Mode for me.

**Comment by DonOregano** [comment]
Happens to me too using Heroes Mode (though I have not tried without)

**Comment by TehGOOSE** [comment]
Oh can confirm, we did have the hero's mode enabled, sorry left that out.

**Comment by wayneb64** [comment]
So only Hero's mode is broken in CQUI?

**Comment by TehGOOSE** [comment]
Ill test a game without heros after work, sadly cant yet.

**Comment by ToggoStar** [comment]
I can confirm: The production menu does not work properly with the heroes mode activated, but works fine without it.

**Comment by wayneb64** [comment]
Thanks, that's good news.

**Comment by Infixo** [comment]
Fixed, PR waiting for an approval.

**Comment by Tfifa** [comment]
greatpeople panel no hero view

**Comment by Infixo** [comment]
@Tfifa Update Real Great People mod to version 4.0. I posted it yesterday.
