### ISSUE TITLE
idea - add a hotkey for "spread religion"

### ISSUE THREAD

**Issue by alexeyOnGitHub** [civfanatics/CQUI_Community-Edition#206]
I think it would be useful to add a few more shortcuts (shown in CQUI configuration panel):
* spread religion (for religious units)   - maybe "s" key?
* heal (for religious units)   - maybe "h" key?

**Comment by alexeyOnGitHub** [comment]
also about hotleys in general - do you guys (@Infixo , @the-m4a ) think you can add a sample PR or a wiki page showing how to add a hotkey support for a certain action?
if we have a good documentation piece , this would help people add their own shortcuts for various things, thus improving the overall game usability.

**Comment by the-m4a** [comment]
I noticed a few other mods have added their bindings configuration to the standard Civ6 Key Bindings config, which brings to mind a couple of things:

1. Should CQUI also put any key bindings here in this menu?
2. Can the CQUI Settings be added to this menu entirely?  (as an option under Application, on the left side there?)
![image](https://user-images.githubusercontent.com/8787640/103262691-8f993980-495a-11eb-9c26-744c03a1061c.png)

Regarding the key binding stuff... I will go add a short wiki page

**Comment by the-m4a** [comment]
Added wiki page: https://github.com/civfanatics/CQUI_Community-Edition/wiki/Adding-Key-Bindings-for-CQUI

**Comment by alexeyOnGitHub** [comment]
thank you for the excellent wiki page! 

if we move the CQUI hotkeys (or all CQUI settings) to the standard game location as you suggested (sounds like a great idea to me!), will it also enable keys configuration (remapping) by the end-user?

**Comment by the-m4a** [comment]
Not sure if just putting it there alone would take care of that, but if nothing else it'd be nice that it's all in one place
