### ISSUE TITLE
Heroes Tab does not show in the Heroes and Great People screen

### ISSUE THREAD

**Issue by the-m4a** [civfanatics/CQUI_Community-Edition#207]
Per the Steam message board and confirmed locally.  Probably just need to update the XML.  Assuming it's basically that, I'll get a PR up for this tonight.  
Someone on the message boards said that the Sinbad hero may not be functional (hot keys), which if the Hero has hot keys, then that makes sense

![image](https://user-images.githubusercontent.com/8787640/100189819-e9ad6780-2ea1-11eb-8c00-3ae5d1a9aac4.png)

Consolidating the screenshots and save file from the duplicate issue created by @loks1234 (literally a few minutes after I created mine... which means we were creating each of these not knowing the other was creating an issue)

**Screenshots**
Vanilla(CQUI Disabled):
![Screenshot (9)](https://user-images.githubusercontent.com/14857152/100190033-77756b00-2f13-11eb-9622-76cafeb06954.png)
![Screenshot (10)](https://user-images.githubusercontent.com/14857152/100190038-793f2e80-2f13-11eb-9627-a3c9103f4900.png)
With CQUI Enabled:
![Screenshot (11)](https://user-images.githubusercontent.com/14857152/100190040-7a705b80-2f13-11eb-9029-5512a3504dbe.png)

**General informations**
 - OS: Windows 10
 - Version 1.0.7.9
 - Expansion Gathering Storms
 - Other mods: YnAMP,Extended Policy cards,Better Screen Reports

**Save game and logs**
Save File Attatched:
[AutoSave_0038.zip](https://github.com/civfanatics/CQUI_Community-Edition/files/5594742/AutoSave_0038.zip)

**Comment by loks1234** [comment]
I seem to have reported a bit late

**Comment by the-m4a** [comment]
Oy... the Heroes lua code is off in the Babylon DLC.  Good times!

```lua
-- This file is being included into the base GreatPeoplePopup file using the wildcard include setup in GreatPeoplePopup.lua
-- Refer to the bottom of GreatPeoplePopup.lua to see how that's happening
-- DO NOT include any GreatPeoplePopup files here or it will cause problems
-- include("GreatPeoplePopup");
```

Given this and the other files that are a part of this DLC I have a feeling it's not just the GreatPeoplePopup that's not working - GreatWorks, NotificationPanel, ToolTipHelper?

**Comment by loks1234** [comment]
![Screenshot (12)](https://user-images.githubusercontent.com/14857152/100210085-933b3a00-2f30-11eb-9cee-cef85b697ff9.png)
Unable to scroll on the heroes page even with the workaround from steam

**Comment by the-m4a** [comment]
I swear, honestly, I had just completed completing adding multiple heroes in order to check the panel scrolling and then the email from GitHub popped up saying what you said, which is amazing timing.

If the scrolling isn't working, that's a Firaxis thing... by commenting out those lines in the modinfo file, it means CQUI doesn't do any modifications to that panel.  My game got messed up when I essentially forced "find a new hero" to happen more than once in a turn (in the same city)...

I'm going to create a review here shortly -- will see if I can download your save file and have a look and see if it functions there.

**Comment by the-m4a** [comment]
Argh - yep it's another CQUI thing.  Found it.  FormatTableAsString was missing.  I wonder why CQUI has it's own version of supportfunctions.lua... perhaps that's a good candiate for the "reduce replacements" stuff.

The panel itself is not pretty, as it's area where "discovered" and whatnot is showing is oversized because CQUI altered it when building the Great People part of the panel... so there's work that should be done to prettify things.  
The GreatPeople stuff lives off in its own files though, so it's a bit tricky.

![image](https://user-images.githubusercontent.com/8787640/100218807-11182a80-2eca-11eb-92b7-50c41becd8cb.png)
