### ISSUE TITLE
Hero Tab not showing up in the Great People and heros Window

### ISSUE THREAD

**Issue by loks1234** [civfanatics/CQUI_Community-Edition#208]
**Describe the bug**
Hero Tab not showing up in the Great People and heros Window

**To Reproduce**
1. Click on "Great People & Heroes" Button on the top left
4. You will see that the Heroes tab is missing

**Expected behavior**
Heroes tab should be present along with their description and status(recruited,dead,Waiting to be recruited)

**Screenshots**
Vanilla(CQUI Disabled):
![Screenshot (9)](https://user-images.githubusercontent.com/14857152/100190033-77756b00-2f13-11eb-9622-76cafeb06954.png)
![Screenshot (10)](https://user-images.githubusercontent.com/14857152/100190038-793f2e80-2f13-11eb-9627-a3c9103f4900.png)
With CQUI Enabled:
![Screenshot (11)](https://user-images.githubusercontent.com/14857152/100190040-7a705b80-2f13-11eb-9029-5512a3504dbe.png)

**General informations**
 - OS: Windows 10
 - Version 1.0.7.9
 - Expansion Gathering Storms
 - Other mods: YnAMP,Extended Policy cards,Better Screen Reports

**Save game and logs**
Save File Attatched:
[AutoSave_0038.zip](https://github.com/civfanatics/CQUI_Community-Edition/files/5594742/AutoSave_0038.zip)

**Comment by the-m4a** [comment]
Hah, thank you!  You have better screen shots than I put in 👍

**Comment by the-m4a** [comment]
Yours is the dupe since I somehow managed to beat you by like... 10 minutes or so :)

**Comment by the-m4a** [comment]
Closing as I incorporated this information into the other post
