### ISSUE TITLE
idea - support hotkeys configuration for Air units - range attack and rebase

### ISSUE THREAD

**Issue by alexeyOnGitHub** [civfanatics/CQUI_Community-Edition#22]
one of the things that makes the late game painful for hands is extra mouse clicks for Air unit range attacks and rebase operations. there is a hotkey for a range attack, but it conflicts with "camera left".
let's see if we can allow these things to be configurable in UI:
* range attack for air units
* rebase for air units

**Comment by alexeyOnGitHub** [comment]
hi @alimulhuda ! would you be interested in adding/improving support for these and other hotkeys? I know from my naive "market research" that many people prefer hotkeys over mouse when possible (I am one of those too!). ideally I would want to see all/most game actions mapped to some keys, with the ability to configure this in a config dialog. 

the problem with mouse actions is that they are likely to contribute to repetitive strain injury on your wrists, which is a common issue for (older) people spending a lot of time on computer.

**Comment by alimulhuda** [comment]
I was also thinking about working on this one. I'll take a look on the weekend. But it might be slow going, I'm not sure how much time I can stick into it, specially the part with settings screen to allow user configurability.

I was also going to consider removing some of the CQUI shortcuts if they can be configured in the base game. For example if the base game allows users to map WSAD keys for the map panning then I would prefer to remove it from CQUI and let the base game handle it. Any thoughts or objections for that kind of change?

**Comment by alexeyOnGitHub** [comment]
if the base game handles those shortcuts, I can't think of a good reason for them to be in the mod. let's remove them.

**Comment by alimulhuda** [comment]
So just a quick update, I was just playing around with the FireTuner and it looks like the fix might be something very simple. I think if we just bind the keystroke to the following functions we should be able to get the thing working.
```
UI.SetInterfaceMode(InterfaceModeTypes.REBASE)
UI.SetInterfaceMode(InterfaceModeTypes.AIR_ATTACK)
```
I tried running those commands in the WorldInput context after selecting an air unit and the game behaved the way it would if you pressed the respective button. Hopefully sometime during the week I'll create a branch and go through the pull process to get you all to sanity test it.
