### ISSUE TITLE
Notification Log is shifted down the screen with December 20 update

### ISSUE THREAD

**Issue by wayneb64** [civfanatics/CQUI_Community-Edition#224]
![image](https://user-images.githubusercontent.com/35745304/102701456-cf567780-421c-11eb-930b-f295cfb4bd4e.png)

**Comment by the-m4a** [comment]
I'm having a dumb moment... where does the notification log come from?

**Comment by alexeyOnGitHub** [comment]
I think this is from Notification Log mod - https://steamcommunity.com/sharedfiles/filedetails/?id=1459493312

**Comment by wayneb64** [comment]
My apologies, I totally forgot that I had added the Notification Log mod. Doubtful the change has anything to do with CQUI. (It would make a nice edition however as it's very handy at times.)

**Comment by wayneb64** [comment]
Update: Dec 29 @ 12:20pm
Fixed script error caused by a missing reference to a new file added in a recent base game update.
