### ISSUE TITLE
Translation to other languages

### ISSUE THREAD

**Issue by TomahawkNSK** [civfanatics/CQUI_Community-Edition#229]
I made a full Russian translation of CQUI. Then I tried to create a branch in the repository to make a merge request later, but I didn't have access rights. How can I contribute to this repository?

**Comment by alexeyOnGitHub** [comment]
please create a fork of the repo, then submit a pull request. someone from the team will review and +1 it. I can review it too

**Comment by the-m4a** [comment]
@TomahawkNSK that's awesome! thank you, we will look for the PR 👍
