### ISSUE TITLE
Cleaning up the Heroes and Great People panel - would like opinions

### ISSUE THREAD

**Issue by the-m4a** [civfanatics/CQUI_Community-Edition#233]
I'd like some opinions from y'all, @alexeyOnGitHub , @alimulhuda , @Infixo --
I have been working on cleaning up the Heroes panel, as I really dislike how compact it is at the moment.  That work meant some refactoring of the code to do the dynamic height scaling of the panel and a bit of tidying of the XML.  That tidying and the changes to the hero panel brought about 2 questions:

1. Where should the patronage/recruit/reject buttons and "Cannot Recruit" message be located?
I like both the buttons and the "Cannot Recruit" message showing "inside" the paneling, as shown for the Great Merchant and Great Scientist, respectively.  The drawback (barring additional adjustments) is that it leaves a lot of room between the bottom of the "paneling" and the scroll bar.  This blank area does match the blank area on the top (like above Great Engineer, for example)...
(Note: the "Cannot Recruit" for the Scientist is photoshopped in, showing where it would be, as the game at this point should have no reason to deny my ability to recruit...)

![image](https://user-images.githubusercontent.com/8787640/103436339-2f5efd80-4bcf-11eb-8812-3a1d617dadaf.png)

2. I modified the Heroes panel so that each "Hero Instance" is 350 pixels wide (instead of the default 214), made the font brighter, added the home city (when claimed) and adjusted how the Stats (lifespan, movement, etc) are displayed.  350 wide felt like the icons + Ability/Command info was not so squished; any wider felt like too much.   Thoughts?

![image](https://user-images.githubusercontent.com/8787640/103436445-2d496e80-4bd0-11eb-9307-605d1ec79cc5.png)

Also, happy new year, y'all. I really appreciate that we all have been able to keep this very cool mod alive.  Over 24,000 subscribers!

**Comment by alexeyOnGitHub** [comment]
I like the design for the Great Merchant and Great Scientist in the image.
no strong opinion on the heroes panel. I actually have been using Sukritact's Great People screen for a while (https://steamcommunity.com/sharedfiles/filedetails/?id=1517706192).  I do not mind trying that screen from the CQUI again.

**Comment by the-m4a** [comment]
I created a PR for this
