### ISSUE TITLE
Steam page for the mod inaccessible 2021/01/21

### ISSUE THREAD

**Issue by BlackSmokeDMax** [civfanatics/CQUI_Community-Edition#238]
For the last few hours (at least), the Steam mod page is inaccessible via the Steam program or via web browser.

Was this intentional, or is something set wrong accidentally? Or, of course, the typical "just another weird Steam issue"? (I should note that my other mods seem to be accessible with no issues)

Seem to be able to subscribe/unsubscribe fine, so there is that, and the most recent update downloaded just fine.

Here is the error message shown by Steam:

Sorry!
An error was encountered while processing your request:

The item is either marked as hidden or you do not have permission to view it.

**Comment by alimulhuda** [comment]
@the-m4a When you get a chance could your try to reupload to Steam. Not sure if this is something that is affecting all civ workshop items or just CQUI. I tried to search for it and it showed no results, normally it would at least show some other branches or something. A day ago it looked like it was just CQUI that was not searchable or accessible but now I can't search for any mods.

**Comment by the-m4a** [comment]
ok weird.  it didn't give me any indication of trouble the other night when I uploaded it, but going now says I needed to re-up on the user agreement in order to publish. 

Thanks @BlackSmokeDMax and @alimulhuda - sorry I didn't see this a couple of days ago.
Working on fixing it now

**Comment by the-m4a** [comment]
ok after accepting the agreement literally 3 times, I think it's available again.

**Comment by alimulhuda** [comment]
It still doesn't show up in the search for me, but that might be some kind of caching issue. But I can confirm that I can use the link we have in our readme to access it again.

**Comment by the-m4a** [comment]
I think just caching - I opened up an inprivate window and did a search and it shows up
![image](https://user-images.githubusercontent.com/8787640/105611556-e6800c00-5d6a-11eb-94b8-a762be4f410e.png)


why it's #4 on this list when it has more than 25K subscribers now, I have no idea.  I do not understand Steam's search algorithm
