### ISSUE TITLE
Investigate: City Banners not appearing with only R&F Enabled

### ISSUE THREAD

**Issue by the-m4a** [civfanatics/CQUI_Community-Edition#24]
Issue from Workshop discussion (Penpa):

Is there also a fix for city banners not showing up coming at a later date? I have tried testing it by disabling every other mod except for CQUI but it still doesn't show city names and not being able to ESC out to the main menu. This only happens when R&F is enabled. With R&F disabled the mod works correctly. This is why I assumed it only worked with GS since this seems to not be an issue with GS people. Also, I double checked and cleaned out my mod folder or unsubscribed from previous versions multiple times, and I still get the issue.

**Comment by the-m4a** [comment]
d'oh! I should've said I was going to work on this :)  I'm going to send a PR right now

**Comment by the-m4a** [comment]
@alimulhuda I apologize for not assigning this to myself before you had done so.   Hopefully you catch this before getting far into making changes :/

**Comment by alimulhuda** [comment]
No worries. I'm just looking through the diff and I'll do a quick sanity test then put my approval on the PR.

**Comment by hartmark** [comment]
I still have no city-banners on my GatheringStorm game
https://www.dropbox.com/s/fft01ls0njd8n99/%28PYDT%29%20Play%20This%20One%21.Civ6Save?dl=0

**Comment by the-m4a** [comment]
@hartmark - I can't get the file to load.  It shows the standard loading screen, pops up a dialog that says "Shaka paused the game" and then it just goes to the mostly blank "Loading, Please Wait..." screen...  and it just sits there.

It's not showing me what other Mods you might've had installed, including CQUI.  What happens if you create a new game?
![image](https://user-images.githubusercontent.com/8787640/84092566-98212700-a9ac-11ea-825f-09c97c2cf1c0.png)

**Comment by hartmark** [comment]
@the-m4a i forgot to mention it's a hotseat game from playyourdamnturn.com

So try load it as a hotseat

**Comment by hartmark** [comment]
@the-m4a were you able to load the game as hotseat?

**Comment by alimulhuda** [comment]
@hartmark I don't have all the DLCs you have so I couldn't load it. I'm missing Khmer, Nubia and Persia. But I did try to create a new hotseat game with the mod and I can see the city banner when I found my first city.
Are you sure you are playing with the latest version and that you have only one version of the mod active? For duplicates check the My Games mod folder (Documents\My Games\Sid Meier's Civilization VI\Mods) and the steam workshop folder for Civ6 (C:\Program Files (x86)\Steam\steamapps\workshop\content\289070). When checking the folders go into every subfolder and check which mod it refers to by looking for the *.modinfo file.
Did you create the game or did someone else create the game?

Also you can upload your Lua.log and Modding.log from Documents\My Games\Sid Meier's Civilization VI\Logs. That might give us some clues as to what is going on.
Follow the steps below to keep the log files small.

1. Quit Civilization 6 if running
2. Start Civilization 6 (Log files get overwritten every time you start the game)
3. Load your save game and go to where you see the issue
4. Quit Civilization 6
5. Upload the two log files

**Comment by hartmark** [comment]
It seems to be related to #36 as I had done the hack for the workshop version of the mod, now I have downloaded it manually.

**Comment by hartmark** [comment]
I'll continue my post there as this issue is closed
