### ISSUE TITLE
FYI - I pushed an update to the Workshop that has at least some fixes...

### ISSUE THREAD

**Issue by the-m4a** [civfanatics/CQUI_Community-Edition#243]
The fixes in branch m4a-jan2021updatesfix appear to at least take care of the DiplomacyDealScreen and the CityBanners.  Non-obvious error messages that required minor fixes.

The code in that branch includes the CityStates Inline Quest stuff and a fix for the Vanilla unassigned Citizens bug.

**Comment by Gliptal** [comment]
Thanks for the hotfix!

**Comment by Gliptal** [comment]
City names are now correct in m4a-jan2021updatesfix, but banners for all the player's cities are now missing. You can still enter the city view by clicking on the city center.

![Screenshot (6)](https://user-images.githubusercontent.com/3907646/106208346-81da0c80-61c3-11eb-8ca1-ad3cd1d8bcd3.jpg)
