### ISSUE TITLE
Promoting this Fork to a Project

### ISSUE THREAD

**Issue by the-m4a** [civfanatics/CQUI_Community-Edition#246]
@alexeyOnGitHub - I sent a note over to GitHub support to see if it's possible to have our repo here promoted as its own project without losing the file history, if for no other reason just to enable the searching within our files.  I'd seen online that hitting up the GitHub support was a way to make this happen.  I don't own the project, though, so they may have you be the one that makes such a request...

One of these days I need to figure out how to send you a message without having to create an issue for it, as well. :)

**Comment by alexeyOnGitHub** [comment]
ok, please check your gmail address - I have sent you a note there.
