### ISSUE TITLE
Civ Trade Deals Are Bugged

### ISSUE THREAD

**Issue by Darknote** [civfanatics/CQUI_Community-Edition#249]
**Describe the bug**
When you go to Deals in Diplomacy, all categories are stuck in the drop down position. You can't click the down arrow to see cities, resources, works of art, etc.

Trade Deal bug. It doesn't show anything in the Trade menu besides gold, and even that's sketchy.

**To Reproduce**
1. Play a normal game.
2. Try to initiate Deals in the Diplomatic menu with any AI Civ.
3. See that it's completely bugged.

**Expected behavior**
Trade deals working as intended before today's (6 Feb 2021) patch.

**Screenshots**

**General informations**
 - OS: Windows 10
 - Version [e.g. 1.0.0.256]
 - Expansion: RaF and GS
 - Other mods: CQUI, Environment Skin Sid Meyers Civilization, Extended Diplomacy Ribbon, Good Goody Huts, Historic Speed, Real Strategy, Remove GDR, WASD Camera Panning,Zees Fewer Trade Offers, Surprise Climate Change, Total War: Warfare Expanded (And it's RED counterpart), Scapeh's WMD City Razing.

**Save game and logs**
Linked below.

Thanks for your help!

**Comment by Darknote** [comment]
Logs:
https://drive.google.com/file/d/1LQQb9BS2bFRS4_lyi3I8qxnOECuYDjWM/view?usp=sharing

**Comment by ympaik87** [comment]
I'm having the same issue. :(

**Comment by the-m4a** [comment]
Looking into it now.  I checked this last night and it seemed okay, so I'm wondering if the upload somehow managed to get bungled?

**Comment by the-m4a** [comment]
Huh.  @Darknote the logs were very handy, and while I was just typing out that I didn't have issues locally... I noticed that the deal screen I had opened with Pedro showed Norway in the top part of the deal view.  What is particularly frustrating though is that the error messages don't always show up in the tuner to see what's up.  (I typed up most of this response like 5 hours ago and never hit "comment", d'oh!)

**Comment by Darknote** [comment]
I'm happy to hear that the-m4a! I checked the save file now and the trade deal is fixed! Thank you so much! 👍 

I will close this ticket now :D

**Comment by the-m4a** [comment]
@Darknote - aah, not so fast :)  -- the workshop version right now is from the 29th (the previous one), as I figured reverting was better than making everyone wait when I wasn't sure what was happening.

That said, I think I have the fix now, including a nagging issue where the Diplomatic Favor and Gold buttons would sometimes have colored text or the "important" icon showing when they shouldn't have been doing so.  I'm going to test out a little more and if all looks good, I'll push it to the workshop.  If _that_ one looks ok, then we should close this. :)

Thanks again!

**Comment by Darknote** [comment]
Alright man! You're awesome :D

Thanks for maintaining the mod as well. It is literally crucial.

Best wishes,
Darknote

**Comment by the-m4a** [comment]
You're welcome, it's mostly fun for me. :)  Also agree on the crucial - when I get the itch to play Civ, the city screen in the unmodified game just kills me.  That's what got me trying to put this back together last April or so.  Fast forward nearly a year, and now the thing has 27k subscribers in the workshop.  It's pretty neat.

**Comment by Darknote** [comment]
1000% man (or woman). And we all thank you for the work you put in :'( !!

If there is something you need help for, let me know.

**Comment by the-m4a** [comment]
Apparently it's still bugged - I reverted it back to the Jan28th version again.  If you're able to try a version downloaded from here - that latest failed attempt is the code in the m4a-jan2021-pt2 branch

**Comment by Darknote** [comment]
Alright will try it out tomorrow morning (8+ hours). Currently very late here. :( 

Good night!

**Comment by Darknote** [comment]
@the-m4a I just tried out the m4a-jan2021-pt2 branch and it bugs out in my save game as usual. Steam version (old one) works without issues.

I believe the trade screen bugs out when we discover resources/great works, as it works fine with just gold.

**Comment by the-m4a** [comment]
@Darknote any chance you grabbed logs again?  I still can't get this to happen locally!  Such a strange issue.

**Comment by Darknote** [comment]
Sure thing. Hope it helps:
https://drive.google.com/file/d/1E_jhlmFAubzkY3vIzZlU0EXl48kJlcA8/view?usp=sharing

I started a game, went to trade deals, saw that the game is bugged, and Alt-F4 (But created an extra luxry Incense with Maui Hero).

**Comment by the-m4a** [comment]
helpful, once again, thank you.  Okay, it for sure is a conflict with Extended Diplomacy Ribbon (EDR).  I understand why, as well: in the current workshop version of CQUI (the working one), basically the CQUI files never get loaded.  CQUI has a "load order" of 0 for these things, and EDR has a load order of 13000 (!!).  

I compared the EDR version of "DiplomacyDealView" and the unmodified version from Firaxis
- Vanilla/XP1 file:  6 lines different
- XP2: 6 lines different (in DiplomacyDealView.lua), 2 lines different (in DiplomacyDealView_Expansion2.lua).

EDR adds the same Icon that CQUI does - the " ! " though it's used in different contexts (EDR uses it to signify an item be tradable).

I am partial to what the CQUI trade screen looks like, so I'm going to see if I can force an override.  EDR has 45000+ subscribers, CQUI is over 27000 now, so it's worth the effort to make these play nice together.

**Comment by the-m4a** [comment]
Got it, I think - I'll push the code up... if you wouldn't mind giving it another shot, I would appreciate it! :)

Pic below shows Extended Diplomacy Ribbon and CQUI playing nicely together; EDR always shows the ribbon, even in the trade screen (_Diplomacy Deal View_ screen).... and this is the modified CQUI trade screen with the fancy buttons and whatnot.

![image](https://user-images.githubusercontent.com/8787640/107352019-33105a80-6a80-11eb-89e7-4c99bc823dcd.png)

**Comment by Darknote** [comment]
@the-m4a it works now! Flawlessly even! Thank you very much 😄 
![image](https://user-images.githubusercontent.com/3754507/107367966-a2ba3000-6ae8-11eb-8afe-df88302a075e.png)

And thank you a lot for making the mods compatible. You're awesome man 🤗

**Comment by Darknote** [comment]
Almost flawlessly. There is texture flickering when hovering over random buttons, but when you hover back, the flickering doesn't appear. Very interesting.

Logs: https://drive.google.com/file/d/18izg5sQbnuSj-OwW3zJJGnt-nANRNZrI/view?usp=sharing

**Comment by Darknote** [comment]
No more flickering. I guess it was temporary. Going to close the ticket if it's alright with you!
