### ISSUE TITLE
Settings not showing

### ISSUE THREAD

**Issue by the-m4a** [civfanatics/CQUI_Community-Edition#25]
Well... I did test it yesterday, however, I reproduced the issue where the settings aren't showing at all now.

Which is weird.

And the suggested fix of moving the database load back into the InGameActions section didn't seem to take care of it... so I'm investigating that right now and will update ASAP.

**Comment by alimulhuda** [comment]
Do you think it might be better to roll back both the changes to .modinfo file and just republish the mod on the workshop. This way there is less pressure to fix it right now and people on the workshop can continue to use it. In case you didn't see the comment I added on the Pull Request I'm pasting a link to my comment here. I don't think it's an issue with just settings page not showing.

https://github.com/civfanatics/CQUI_Community-Edition/pull/21#issuecomment-639743547

**Comment by the-m4a** [comment]
I also tested - the AffectsSavedGames should be able to stay at 0 and it appears that while there's a way to do the save settings and apply to other games, it's not as easy as it appeared when I made the change last night.

From your lua.log:
```

Runtime Error: C:\Program Files (x86)\Steam\steamapps\workshop\content\289070\2115302648\Assets\UI\CQUICommon.lua:64: attempt to index a nil value
stack traceback:
	C:\Program Files (x86)\Steam\steamapps\workshop\content\289070\2115302648\Assets\UI\CQUICommon.lua:64: in function 'PopulateComboBox'
	C:\Program Files (x86)\Steam\steamapps\workshop\content\289070\2115302648\Assets\cqui_settingselement.lua:337: in function 'Initialize'
	C:\Program Files (x86)\Steam\steamapps\workshop\content\289070\2115302648\Assets\cqui_settingselement.lua:421: in function '(main chunk)'
	[C]: in function '(anonymous)'
Lua callstack:
Error loading file where=, file=C:\Program Files (x86)\Steam\steamapps\workshop\content\289070\2115302648\Assets\cqui_settingselement.lua
InGame: Loading InGame UI - C:/Program Files 
```

Those errors appear when the UpdateDatabase command is in <FrontEndActions> rather than <InGameActions>.  The specific line of code that is failing:

```
    if(GameInfo.CQUI_Settings[setting_name]) then
```
The CQUI_Settings (which is the name given to the UpdateDatabase statement in the modinfo file) aren't available in GameInfo, so the call to PopulateComboBox fails.  While that specific error may not explain why the entire UI doesn't appear, it does show that the settings are not available in the Game context.  I am not 100% clear on why data done in FrontEndActions is not available in Game context somehow - maybe it is, but how the lua script is currently attempting to access it does not work...

**I will put the UpdateDatabase section back in InGameActions and update the mod on Steam so that can at least get functioning again.**

In the meantime - I was looking into a way to try and persist the settings.  I found something interesting, which I'll paste below.

To review, this is what I have observed with the settings:
Scenario 1:
1. Start Game
2. Change CQUI Settings
3. Play at least 1 turn, Save Game
4. Quit to main menu
_5. Resume (just saved) game_
6. RESULT: CQUI Settings changed in step 2 remain

Scenario 2:
1. Start Game
2. Change CQUI Settings
3. Play at least 1 turn, Save Game
4. Quit to main menu
_5. Create new game_
6. RESULT: CQUI Settings changed in step 2 are lost

I found this post on CivFanatics from Gedmon, the author of the YaMP and other mods, explaining a way to persist state, perhaps:
https://forums.civfanatics.com/threads/saving-loading-simple-tables-with-a-game.609397/

I found a mod that used that example code (or a version of it) from that post, but haven't found anything else as of yet:
https://github.com/Gedemon/Civ6-Historical-Spawn-Dates

**Comment by alimulhuda** [comment]
The settings are supposed to be saved per savegame. For new games I believe it will go back to default. I don't think it was supposed to update the default settings. So just to clarify, you are trying to get the settings to be more of a global setting instead of a per game setting. Is that right?

**Comment by the-m4a** [comment]
Yes, that's the idea.  That's more or less what I thought the design should be... most of those settings - like auto-applying lenses, showing luxuries on the top panel... I look at them as things I'd want applied to all games I play, not just the one I'm playing at the moment.  It doesn't make a lot of sense to be a per-savegame, most of those things?

**Comment by the-m4a** [comment]
sent a PR - https://github.com/civfanatics/CQUI_Community-Edition/pull/26

**Comment by the-m4a** [comment]
I'm also curious - as I'm pretty well versed in SQL... this is from the cqui_settings.sql file:
```
INSERT OR REPLACE INTO CQUI_Settings -- Don't touch this line!
  VALUES  ("CQUI_AlwaysOpenTechTrees", 0), -- Always opens the full tech trees instead of the civic/research picker panels
      ("CQUI_AutoapplyArchaeologistLens", 1), -- Automatically activates the archaeologist lens when selecting a archaeologist
      ("CQUI_AutoapplyBuilderLens", 1), -- Automatically activates the builder lens when selecting a builder
```

INSERT OR REPLACE... why would we ever want to replace?  If the settings DO persist in some way, does this command overwrite those things each time a new game is loaded?

I really wish the fine people at firaxis did a better job of documenting this stuff.  I can see why people get burned out on keeping these things up to date.

**Comment by alimulhuda** [comment]
> INSERT OR REPLACE... why would we ever want to replace? If the settings DO persist in some way, does this command overwrite those things each time a new game is loaded?

I think the database is just a place to store default values, nothing else (based on the comment block in the file start). The actual values the mod uses get stored wherever the GameConfiguration object stores stuff. Since it is only default values in the database, I think it is the safer thing to do to make it more resilient to anything outside the mods control.

> I really wish the fine people at firaxis did a better job of documenting this stuff. I can see why people get burned out on keeping these things up to date.

The more I try to look into how/why certain things happen, the more impressed I am of the modding community. It's amazing how much they managed to do with the very little they have given to them.

**Comment by stagnate** [comment]
Without any Civ modding context, when I have seen "INSERT OR REPLACE" on the job it is used to avoid SQL errors on key constraints.  If you don't replace then you need to make sure that the insert only happens if the line doesn't already exist (or that any key error is transparent to the user)

**Comment by MateusBelo** [comment]
HI,, Whenever I encounter the first civilization, the dialogue with the other civilization does not appear and the entire screen interface also disappears and it is not possible to click on anything else.
I don't have RF or GS installed.  What can i have done wrong? should i install another mod?

**Comment by the-m4a** [comment]
I was looking at the databases when the game wasn't loaded up, didn't see any of the CQUI things in there... so I have this feeling that it just isn't something that we can do.  Sadly :/

**Comment by the-m4a** [comment]
Closing this.  I'm fairly convinced that this isn't something we can do or is easily done.  There exists directions within the mod to set up cqui_settings_local to accomplish this... it's not a great fix but it's a fix.
Something I'll probably want to look into in the future again, but for now, considering this a won't fix
