### ISSUE TITLE
Wonder videos appear in multiplayer games and get players stuck

### ISSUE THREAD

**Issue by ToggoStar** [civfanatics/CQUI_Community-Edition#253]
**Describe the bug**
With CQUI wonder videos appear in multiplayer games (independent auf the switch in CQUI settings) and the player completing the wonder gets stuck in the wonder video screen. He cannot exit the wonder video screen at all.

**To Reproduce**
- Start a multiplayer game with CQUI enabled.
- Build any wonder.
- The wonder video will play after completion and you will be stuck in the video screen.

**Expected behavior**
- The setting in CQUI settings regarding wonder videos is respected, i.e. no video is shown when turned off.
- If videos are enabled, the wonder video screen can be exited as usual.

**General informations**
 - OS: Windows 10
 - Latest version of the game and mod
 - All
 - We tested a multiplayer game with the other mods we used and did not run into the issue, so I assume the problem is specific to CQUI.

**Comment by m-from-space** [comment]
Can confirm, but I am also playing with ToggoStar, I might be biased.

**Comment by the-m4a** [comment]
@ToggoStar @m-from-space - I'll look into this now.  I don't have any people handy to play a multiplayer game, but hopefully I can see through the code what is up

**Comment by the-m4a** [comment]
Indeed - figured out how to reproduce this issue without needing to be in multiplayer.  Fixing now and will create a PR and upload to the workshop once completed

**Comment by the-m4a** [comment]
@ToggoStar  , @m-from-space  - can you confirm this is fixed?

**Comment by ToggoStar** [comment]
We didn't have a chance to test yet, but probably will do so this weekend. I'll keep you updated! :)

**Comment by ToggoStar** [comment]
Yes, the issue is fixed - thank you!
