### ISSUE TITLE
Added / Modified German localisation to the settings

### ISSUE THREAD

**Issue by Titule1** [civfanatics/CQUI_Community-Edition#257]
Couldn't push the change. I get a permission denied from github, although I created a token etc... dunno

So here's the changed file "Assets\Text\cqui_text_settings_de.xml". I had to rename it and add ".txt" otherwise I couldn't upload it here.
[cqui_text_settings_de.xml.txt](https://github.com/civfanatics/CQUI_Community-Edition/files/6008861/cqui_text_settings_de.xml.txt)

It's still not FINISHED, I just added some missing texts and modified some of the google translations.
(BTW: The space for text is sometimes too small in the screen)

**Comment by the-m4a** [comment]
thank you!  Github is goofy sometimes so I'm not sure what's going on with not allowing you to send that stuff.  I need to get sleep now, as I just pushed changes to the Steam workshop.  I'll check these out tomorrow or this weekend.
