### ISSUE TITLE
Possible bug: AI spies and submarines visible when they shouldn't be

### ISSUE THREAD

**Issue by the-m4a** [civfanatics/CQUI_Community-Edition#260]
From Steam workshop: (user "truncated")

Bug found. I can sometimes see AI spies in my cities and AI submarines too even when I don't have any units close to them. Those units should be invisible. I disabled all other mods and I still see the problem. If I disable CQUI, those units become invisible

**Comment by wayneb64** [comment]
I have noticed the spies for quite some time, several months now it seems. I thought it was some kind of new feature as I kind of like it. No rush to 'fix' this from my point of view. I don't recall seeing an enemy sub I should not have. If they move past any of your units or an allies/city states units you are suzerain of you should see them.

**Comment by RobertDomico** [comment]
Here is a screenshot of what I see.
![PXL_20210301_155702047](https://user-images.githubusercontent.com/5768006/109553462-107ec980-7aa1-11eb-979f-1d03b3025274.jpg)

**Comment by the-m4a** [comment]
I'm totally puzzled on this one.  I cannot figure out how this is supposed to work?
I don't think it's something in the CQUI UnitFlagManager code... but it may still be something in CQUI.

Documenting what I did when I decide to come back to this:
1. Commented out ALL of the CQUI UnitFlagManager code.  So even though CQUI was loaded, there was nothing specific CQUI was doing with UnitFlagManager.
- Placed a Privateer (AI player).  Noted it was not visible.
- Moved warrior next to the plot with the Privateer.  Privateer now visible.
- Moved warrior away.  Privateer no longer visible.  Okay, fine.

2. Repeated step 1 with the CQUI UnitFlagManager code intact.  It behaved the same way.

3. Commented out all of the CQUI UnitFlagManager code.
- Placed the Privateer where I could see the plot from my city, but had no unit immediately adjacent.  Privateer was not visible as expected.
- In LiveTuner, while in UnitFlagManager context, did "Refresh()".  Privateer is now visible.

As best I can tell, #3 should happen without ANY CQUI because of the code in the Refresh() function in UnitFlagManager.lua.  The call to OnUnitVisibilityChanged appears to hinge on whether or not the plot is simply visible, doesn't seem to take into account that the unit is a stealth unit?

**Comment by the-m4a** [comment]
I confirmed that if I call Refresh() from the LiveTuner _without_ CQUI loaded, a previously hidden unit will appear.

This chunk of code in the Firaxis UnitFlagManager just sets the unit visibility to VISIBLE regardless of it being a stealth unit or not.
```lua
				-- If flag is visible, ensure it's being viewed that way; set plot for an update call.
				-- While event will handle in normal case, this is necessary for hotloading and flags are re-created.								
				if pLocalPlayerVis:IsVisible(locX, locY) then
					OnUnitVisibilityChanged(playerID, unitID, RevealedState.VISIBLE);
					if plotsToUpdate[locX] == nil then
						plotsToUpdate[locX] = {};
					end
					plotsToUpdate[locX][locY] = true;	-- Mark for update
				end	
```

CQUI can _not_ call Refresh (which may be possible), or perhaps the bug could be addressed in the Refresh function

**Comment by the-m4a** [comment]
ooh i figured out how to get around it.  yay!  will push up the code changes in a bit and create a PR.
