### ISSUE TITLE
Barbarian outpost banners not visible in barbarian clans mode

### ISSUE THREAD

**Issue by phielp** [civfanatics/CQUI_Community-Edition#263]
In the new barbarian clans mode their camps now have (city) banners, however they won't show up with CQUI enabled.

**Comment by BlackSmokeDMax** [comment]
Concur. I tried both with and without CQUI as well.

**Comment by Zanar27** [comment]
I had the same problem with the barb camp missing banners. I unsubbed and resubbed to the mod which made them come back, although this broke all the banners for units. See the screenshot.
![Civ6](https://user-images.githubusercontent.com/79798273/109422779-53776900-79dd-11eb-8171-0821df996dc0.png)

**Comment by the-m4a** [comment]
?! all units?  That's weird.  What's with all the unit flags floating in the middle of the screen there?  Additionally weird.  Maybe an issue with the Sukritract mod also running at the same time? 
Can you grab the Lua.log file from the My Games\Sid Meier's Civilization VI\Logs folder (if this is still happening)?

just for comparison's sake:
![image](https://user-images.githubusercontent.com/8787640/109780344-c76f6800-7bbb-11eb-9286-9e04114031f0.png)

**Comment by Zanar27** [comment]
I believe this was only with CQUI enabled, but I have been doing some mod trouble shooting and think there might be some interaction with a saved city-state picker that was causing it. My current game works great and only has the occasional barb banner staying despite the camp being gone (fixed on reload).
I've attached the log but my current game has a lot of mods enabled.
[Lua.log](https://github.com/civfanatics/CQUI_Community-Edition/files/6077221/Lua.log)

**Comment by the-m4a** [comment]
Ok - sorry for taking a bit to get back to you.  The log does reveal at least 3 errors with the banners - looks like it may be an issue with another City Banner mod you have loaded: Arstahd's Improved City Banner: https://steamcommunity.com/sharedfiles/filedetails/?id=2118254729

The error stack is this:
```
Runtime Error: H:\Steam\steamapps\workshop\content\289070\2118254729\Exp2\CityBannerManager.lua:1698: attempt to index a nil value
stack traceback:
	H:\Steam\steamapps\workshop\content\289070\2118254729\Exp2\CityBannerManager.lua:1698: in function 'HasEspionageView'
	H:\Steam\steamapps\workshop\content\289070\2118254729\Exp2\CityBannerManager.lua:1278: in function 'CityBanner:UpdateStats'
	H:\Steam\steamapps\workshop\content\289070\2115302648\Assets\UI\WorldView\CityBannerManager_CQUI.lua:199: in function 'CityBanner.UpdateStats'
	H:\Steam\steamapps\workshop\content\289070\2115302648\Assets\UI\WorldView\CityBannerManager_CQUI.lua:1303: in function 'OnDistrictAddedToMap'
	[C]: in function 'func'
	[C]: in function '(anonymous)'
```
That top line on the stack is where the most recent error happens to be - looks like that mod replaces all of the CityBannerManager.lua file _and_ the last update for that mod appears to be prior to the February update, which included a few things Firaxis added to make the banners appear above the barbarian camps.
