### ISSUE TITLE
No city banners under Linux

### ISSUE THREAD

**Issue by StragaSevera** [civfanatics/CQUI_Community-Edition#264]
**Describe the bug**
Under Linux, no city banners are shown. This problem was fixed some time ago, but now it came back.

**General informations**
 - OS: Arch Linux
 - Version: commit bbee4be from the 'main' branch.
 - Expansion: All
 - Other mods: None

**Save game and logs**
[Logs.zip](https://github.com/civfanatics/CQUI_Community-Edition/files/6060106/Logs.zip)

**Comment by the-m4a** [comment]
Boo.  Okay I'll look into this during the week sometime.  Still no Lua.log file in the logs so nearly impossible to tell what's going on from the logs, unfortunately.

Are the banners missing in a specific mode (like the Barbarians clans)?  Or all modes?

**Comment by the-m4a** [comment]
though - I'll push my fix for the Feb 25 update to main tonight, so try again once that's pushed up

**Comment by amirrpp** [comment]
unfortunately still no city banners (without any mods/clans etc)

**Comment by the-m4a** [comment]
d'oh meant to look into this, hadn't been able to get to it.  Will maybe get to it tonight.  Thanks for letting me know.

**Comment by the-m4a** [comment]
it for some reason isn't loading the XML files - CityBannerInstances.xml and CityReligionInstances.xml.  
I got one to load by forcing them to use all lower-case names, which I'm pretty sure did _not_ work a while back and was why I had to give them casing that matched whatever Firaxis has.  

The m4a_barbbannerimprovements branch should be functional... it at least worked on my incredibly slow Linux VM

**Comment by the-m4a** [comment]
https://github.com/civfanatics/CQUI_Community-Edition/tree/m4a_barbbannerimprovements

**Comment by amirrpp** [comment]
yes, everything works for me. That's awesome, thank you.

**Comment by the-m4a** [comment]
awesome! thank you for confirming
