### ISSUE TITLE
No production banners under Windows

### ISSUE THREAD

**Issue by MrStasTr** [civfanatics/CQUI_Community-Edition#265]
**Describe the bug**
When I want to change or start buildings and click on the gear icon in the city lable the production banner doesn't open.
Now I can enter the building banner only when the gear icon appearing in the bottom banners.

**To Reproduce**
1. Go to the city lable
2. Click on the gear icon in the lable of the city
3. Open the only banner of city info, but doesn't open productions banner

**Expected behavior**
When clicking on the gear icon in city lable will open the productions banner.

**Screenshots**
![Frame 4](https://user-images.githubusercontent.com/79908780/109637469-e3442100-7b5d-11eb-9c8e-e498170db33b.jpg)
![Frame 5](https://user-images.githubusercontent.com/79908780/109637473-e4754e00-7b5d-11eb-90b9-b96641ed0960.jpg)
![Frame 6](https://user-images.githubusercontent.com/79908780/109637475-e4754e00-7b5d-11eb-9d36-ddb0e1c3b829.jpg)

**General informations**
 - OS: Windows 10 
 - Version: 20H2 x64
 - Platform: Steam
 - Expansion: All 
 - Other mods: None

Thank you so much!

**Comment by the-m4a** [comment]
Strange.  I don't see this issue - see gif below.  Can you grab the Lua.log file from the My Games\Sid Meier's Civilization VI\Logs folder?  Not sure what it could be without seeing that log...

![gif](https://i.imgur.com/usYDlBG.gif)

**Comment by MrStasTr** [comment]
Hi!
There's Lua.log:

DebugHotloadCache: GameDebug initialized!
Mods: FinalFreak16: Loading Mod - Enhanced Mod Manager.
Test: Test.LUA loaded!
JoiningRoom: OnFinishedGameplayContentConfigure() g_waitingForContentConfigure=true

**Comment by the-m4a** [comment]
Sorry for being slow in my responses - work, life, etc all taking time away from Civ!  That unfortunately doesn't tell me much - it's the stuff seen typically when loading the game.  The Log will reset every time you load up Civ, so you'd have to grab that log once you've closed the game (or while it is still running).

**Comment by WebsiteDeveloper** [comment]
@the-m4a Any news on the PR concerning this?
I have the same issue
