### ISSUE TITLE
No UI during trade screen

### ISSUE THREAD

**Issue by darreljnz** [civfanatics/CQUI_Community-Edition#266]
**Describe the bug**
Every time I open the trade screen with CQUI enabled I get the leader displayed but no other UI. None of the UI responds and I need to kill Civ 6 from task manager.

I have never run a mod before. I'm running no other mods. I have vanilla + gathering storm via Epic Games store.

This is on the February Update patch and I'm using mod version 2.3.

**To Reproduce**
1. Start a new game
2. Find any civ
3. Open diplomatic screen
4. Select "Make Deal"

Attached save has Hungary ready to talk to Japan.

**Expected behavior**
Trade screen displayed.

**Screenshots**

**General informations**
 - OS: Windows 10 Home
 - Version: 1.0.10.15
 - Expansion: Gathering Storm
 - Mods: Just CQUI

**Save game and logs**
[MATTHIAS CORVINUS 11 3600 BC.zip](https://github.com/civfanatics/CQUI_Community-Edition/files/6082880/MATTHIAS.CORVINUS.11.3600.BC.zip)

**Additional context**
None

**Comment by loks1234** [comment]
latest mod version seems to be 2.4. Try after updating the mod.

**Comment by the-m4a** [comment]
Try downloading the mod from here if you haven't already: https://steamworkshopdownloader.io/download/2115302648
That site seems to have the up-to-date version.  Steamworkshop.download or whatever it is doesn't seem to get an updated one, its weird.

**Comment by darreljnz** [comment]
Yes, that fixed it. Thanks. Yes, I downloaded the latest from steam workshop and it was 2.3.
