### ISSUE TITLE
Banner and Unit improvements for Barbarian Clans mode

### ISSUE THREAD

**Issue by the-m4a** [civfanatics/CQUI_Community-Edition#269]
After playing like, 5 minutes of the new mode I was just feeling the information presented was lacking.  So I wanted to work on it a bit, and have been tossing around some ideas.  Would like some feedback, especially on the "you can hire this clan" one.    

Image mash-up showing all of the pieces involved, explanations below:
![image](https://user-images.githubusercontent.com/8787640/110277002-416f6a80-7f89-11eb-947d-b278b415ec38.png)

I didn't want to have to mouse-over in order to see what clan a unit belonged to, so they all get their little clan icons now:
![image](https://user-images.githubusercontent.com/8787640/110281280-4506ef80-7f91-11eb-93de-a16cd131c4a4.png)

This icon shows when you have bribed a clan, with number of turns left.  The same icon that shows on the unit flag (default from Firaxis)
![image](https://user-images.githubusercontent.com/8787640/110283311-b85e3080-7f94-11eb-8cb8-e40e790a8a19.png)

This "star" shows you can hire a unit from the clan.  I wanted something smaller than a full icon, because it's something that would be very common.  Just felt like having that always be a thing would be too much.
![image](https://user-images.githubusercontent.com/8787640/110277818-e474b400-7f8a-11eb-8317-0dc439b01f70.png)

Few things in this one:
- I have been trying different spots for that star, I liked it better on the upper right but noticed it'd start getting cluttered with a unit stationed in camp.
- The blue sword icon indicates you (player) have incited them against someone else.  It shows a red sword if someone has incited against you.  (These are the same two icons shown on the "unit flag" if either of those conditions exist.
- The "!" icon is if you can pay to ransom to get one of your units back (Builder or Settler I assume - whatever they can capture)
![image](https://user-images.githubusercontent.com/8787640/110280730-2bb17380-7f90-11eb-9c30-b2206468e5f5.png)

**Comment by loks1234** [comment]
Also Barbarian banner seems to be persistent even after completely razing the outpost. Can you please fix that along with these additions.

**Comment by the-m4a** [comment]
that should be fixed.  the only way i can get that to reproduce is if I added a barbarian camp to the map (using the Live Tuner) and did _not_ set the player as Barbarians first.  The code to remove the banner when the camp is razed is mostly untouched by CQUI, it's as-is from what Firaxis did.  If you're for-sure still seeing the banners, I'll keep plugging away at it and see if I can get it tracked down. :)

**Comment by loks1234** [comment]
Just tried with a new game. The razed banner seems to be going away after saving the game after razing the clan and then loading that save.

**Comment by the-m4a** [comment]
does it go away without the save/load?

**Comment by loks1234** [comment]
nope. It is persistent even after a hundred turns.

**Comment by the-m4a** [comment]
Can you upload the save?  I'm curious if it'd still happen with the code changes in my m4a_barbbannerimprovements branch

**Comment by loks1234** [comment]
After removing the mods it seems to be working fine.

placed a giant death robot above the 'Nuri' city

Save file:
[AMANITORE 148 740 AD.zip](https://github.com/civfanatics/CQUI_Community-Edition/files/6100503/AMANITORE.148.740.AD.zip)

**Comment by loks1234** [comment]
Also can you add barb clan unique unit(Unit which you get after hiring from the clan) icon to their banner.

**Comment by the-m4a** [comment]
Well - I was able to see that the banners still stick around.  It doesn't make any sense because the behavior is no different if I use the Live Tuner to place a camp.  Except when I place one down, it deletes the banner correctly.  I'm falling asleep so I'll have to look into this tomorrow if I get the chance

**Comment by the-m4a** [comment]
I hadn't updated the thread, but I did mention it on the workshop:  the banners issue is because "OnImprovementAddedToMap" is getting called twice for each barbarian improvement (and everything else, for that matter... except goody huts.)

The code that Firaxis has in place does not check to see if a banner already exists when OnImprovementAddedToMap is called, only that the Barbarian Tribe exists.  If they exist, create banner, and since it's called twice for each improvement, you get two banners.

Figuring out why that is called twice is the issue.  I haven't a clue why.  I just know that if CQUI is _not_ loaded, OnImprovementAddedToMap is not called twice.

**Comment by the-m4a** [comment]
Finally figured it out (note: wasn't working on this for 7hrs straight :) -- When the CQUI settings were changed, Reload() was called.  When Reload() is called, it does all those shenanigans with the OnImprovementAddedToMap and stuff.
