### ISSUE TITLE
New Game Crash if barbarian clans mode is enabled

### ISSUE THREAD

**Issue by loks1234** [civfanatics/CQUI_Community-Edition#273]
**Describe the bug**
Game Crashes after ending the first turn if the barb clans mode is enabled.

**To Reproduce**
1. Create a new game with barb clans enabled
2. end turn
3. see the Crash with error

**Expected behavior**
No crash

**Screenshots**
Edit:
![Screenshot (31)](https://user-images.githubusercontent.com/14857152/111026833-a6581400-8412-11eb-9088-ac67ab760903.png)

**General informations**
 - OS: Windows 10
 - Version 1.0.10.15
 - Gathering Storms Expansion
 - Other mods [e.g. YnAMP]

**Save game and logs**
Save Game: [AutoSave_0001.zip](https://github.com/civfanatics/CQUI_Community-Edition/files/6134518/AutoSave_0001.zip)

**Comment by the-m4a** [comment]
thanks for the save!  I am looking into this now as this is obviously unexpected and not one I had seen...

**Comment by the-m4a** [comment]
I can't load it - I can't find whatever the YoRHaCore mod is.  Wasn't on Steam that I could find, and google didn't turn up anything of interest.  What is it?
![image](https://user-images.githubusercontent.com/8787640/111058529-103ce180-8444-11eb-901a-12269d51bd0a.png)

**Comment by the-m4a** [comment]
My guess is it's either YoRHaCore or some other UI mod that causes trouble?  I'm puzzled as to what could be happening.  I downloaded and enabled all of the other mods you have there that affect saved games.  I can't play your exact game without that YoRHaCore mod tho.
![Uploading image.png…]()

**Comment by the-m4a** [comment]
A user on the steam workshop (ubereffect) pointed me to the YoRHaCore mod, so I was able to load the save game.
No crash for me... so now I wonder if it's another UI mod that you have enabled?  A mod that does something with the City Banners  I would think...

![image](https://user-images.githubusercontent.com/8787640/111061053-2489da00-8456-11eb-85c8-a8973b7bf16f.png)

**Comment by loks1234** [comment]
Tried disabling all mods except cqui but it shows the same error.
If I disable the cqui it works just fine with or without other mods.

**Comment by loks1234** [comment]
Just now tried again. Seems to be working fine if you settle the city on first turn.
If I did not settle on first turn and ended the turn the game is crashing.

**Comment by the-m4a** [comment]
Okay... that doesn't make any sense, but sure.  Can you grab the lua.log file?

ooh - just saw your edit.  okay, hadn't tried not settling on the first turn.  lemme see

**Comment by the-m4a** [comment]
Ah - indeed, a repro!
![image](https://user-images.githubusercontent.com/8787640/111061846-2ce41400-845a-11eb-83b3-e6d49a125d37.png)

**Comment by the-m4a** [comment]
heh - apparently game goes crash if you check and see if you are able to hire any units if you don't have a city

Now turn 3, no city founded by me yet, so I think the crash is taken care of now.  I'll upload it to the workshop.
![image](https://user-images.githubusercontent.com/8787640/111062455-b34e2500-845d-11eb-893a-fb5d053d54ca.png)

**Comment by loks1234** [comment]
Awesome. Thanks for updates👍
