### ISSUE TITLE
Extended Policy Cards and Detailed Map Tacks

### ISSUE THREAD

**Issue by wrightc214** [civfanatics/CQUI_Community-Edition#281]
I'd love to see if you could build these two mods into CQUI
Detailed Map Tacks:  https://steamcommunity.com/sharedfiles/filedetails/?id=2428969051
Extended Policy Cards: https://steamcommunity.com/sharedfiles/filedetails/?id=2266952591

**Describe the solution you'd like**
Detailed Map Tacks displays the yield gains for the map pin type on that tile.
Extended Policy Cards displays the empire yield gains on each card.

**Comment by the-m4a** [comment]
Extended Policy Cards should work in conjunction with CQUI.  I don't think there is a conflict between the two, the changes EPC makes to the GovernmentScreen.lua file is pretty minimal and only works if the Better Report Screen mod is also active.

I'll have to look into the other one.  Too tired to make sense of it at the moment, though :)

**Comment by ubereffect** [comment]
I've been using both Extended Policy Cards and Detailed Map Tacks along with CQUI and 50 some odd mods, including over a dozen other UI mods, without issue.

If the mods don't conflict, I see little reason to integrate them. Some people may prefer Alternate Policy Screen to Extended Policy Cards, and Detailed Map Tacks is still very new and updated frequently, both of these points seem like good reasons to keep them separate. Having said that, they sure would fit nicely and really would add to CQUI.

Excellent mods by the way.
