### ISSUE TITLE
Production Queue broke the Barbarian trade interface

### ISSUE THREAD

**Issue by SirChurchill9999** [civfanatics/CQUI_Community-Edition#290]
https://www.reddit.com/r/civ/comments/mwzemg/barbarian_interaction_window_is_broken/

List of mods: https://imgur.com/a/sLEFpOP

Bug screenshot:
![Capture](https://user-images.githubusercontent.com/82127510/115911480-c1676c00-a433-11eb-8db2-d28fb4929e81.JPG)

The issue resolved when I uninstalled CQUI. Another Redditor reported it was "Production Queue" as well.

**Comment by the-m4a** [comment]
Bummer...sorry for not seeing this earlier, I was out of town (left on the 22nd and returned late yesterday).  That said, I also don't reproduce the issue (see pic below).  That's a lot of mods, so it's tough to tell what's happening without the lua.log file and any other context.  Can you grab the lua.log file from your My Games\Sid Meier's Civilization VI\Logs folder?

![image](https://user-images.githubusercontent.com/8787640/116521832-51207680-a889-11eb-97d5-37b7ad8e0e04.png)

**Comment by the-m4a** [comment]
Also - the description on the Steam page mentions the Production Queue mod as being integrated... it is not integrated with CQUI anymore.  I had neglected to remove that from the description (it was removed long ago, I think when Firaxis added their own queue mechanism).

Wow... that's quite the garbled picture there (in the post above), good job, Windows.  Let's try that again:

![image](https://user-images.githubusercontent.com/8787640/116523057-ac069d80-a88a-11eb-9cc8-89622fd9771f.png)

**Comment by the-m4a** [comment]
It appears likely that one of the mods you have running is implementing its own SupportFunctions.lua file and it doesn't have the _FormatTableAsString_ function that was added by Firaxis in October of 2020.

In your Civ Vi mods folder, execute the following command and see if any modinfo files make reference to SupportFunctions.lua:
`findstr -ispc:SupportFunctions *modinfo`

For example, this is what I see when I execute that command... it shows Production Queue as the only one that modifies that file. 
![image](https://user-images.githubusercontent.com/8787640/116534199-14f41280-a897-11eb-8bc4-03ab92166601.png)

If any of them do that, disable that mod and reload.  Note that if the mod "Affects Saved Games", it'll automatically load up if you reload a save file (Production Queue does this).... so you'd have to start a new game in the Barb Clans mode to see.

I explain in the reddit post here: https://www.reddit.com/r/civ/comments/lu3552/the_barbarian_interaction_panel_is_speaking/gwa1kox?utm_source=share&utm_medium=web2x&context=3
