### ISSUE TITLE
Citizen highlights gone in city view and mouse over

### ISSUE THREAD

**Issue by wayneb64** [civfanatics/CQUI_Community-Edition#296]
Not sure this is a bug or an "Enhancement" but the tile highlight (green) of worked tiles is gone with latest. I think I saw a drop somewhat related to this where you could pick colors but that may have been a lenses option. I don't see any menu option to set it back the way it was. My main complaint is that transparent worker icons is not enough of a visual queue for me, need a bit more. Also, locked versus unlocked is really difficult to see. (I am somewhat visually challenged.)

I have the latest release, all content, plus a couple other small mods.

**Comment by the-m4a** [comment]
@wayneb64 was this before or after the most _most_ recent update?  I had messed up the "Citizen Management Lens" when I first updated the More Lenses integrated stuff, but fixed it with the most recent release on the Workshop

**Comment by wayneb64** [comment]
Just tested latest latest and it's working now. Still one weird little thing I think I may have saw before, the green/red don't work on city mouse over until AFTER you open the first city detail.
