### ISSUE TITLE
Translation issue

### ISSUE THREAD

**Issue by Akionka** [civfanatics/CQUI_Community-Edition#297]
**Describe the bug**
Some texts in settings menu are rendered in English, though  they are translated in files.

**To Reproduce**
1. Select Russian language
2. Open CQUI settings

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/42269025/117727418-a85f0900-b1f0-11eb-8ae7-b60eefa25b0e.png)

**General informations**
 - OS: Windows
 - Version: 1.0.12.9 (564030) Epic Games
 - Expansions: Aztecs only
 - Other mods: CQUI only

**Additional context**

**Comment by Akionka** [comment]
Also there are more places where the mod is not translated and I would help with the translation

**Comment by the-m4a** [comment]
I would love some help with the translations!  I have tried to use a thing on Azure to produce some text but it does not work all that great it seems.  Your screen shot shows the CQUI settings, so we can start there...

If you're experienced with Git and want to clone the repo and then do a Pull Request, that works.  If you're not familiar or comfortable with that and just want to compare XML files and paste in parts or all of an XML, that works too.  I am happy to accept whatever you'd like to do.

If you want to look at the two files to compare:
https://github.com/civfanatics/CQUI_Community-Edition/blob/main/Assets/Text/cqui_text_settings.xml
https://github.com/civfanatics/CQUI_Community-Edition/blob/main/Assets/Text/cqui_text_settings_ru.xml

I did a quick compare, here are the tags in the English settings that are missing from the Russian translation (most of which are new to my last update... I didn't do all the localizing work :S )
LOC_CQUI_LENSES_AUTOAPPLYARCHAEOLOGISTLENS_TOOLTIP
LOC_CQUI_LENSES_AUTOAPPLYBUILDERLENS_TOOLTIP
LOC_CQUI_LENSES_AUTOAPPLYSCOUTLENS_EXTRA
LOC_CQUI_LENSES_AUTOAPPLYSCOUTLENS_EXTRA_TOOLTIP
LOC_CQUI_LENSES_AUTOAPPLYSCOUTLENS_TOOLTIP
LOC_CQUI_LENSES_BUILDERDISABLEDANGEROUS
LOC_CQUI_LENSES_BUILDERDISABLEDANGEROUS_TOOLTIP
LOC_CQUI_LENSES_BUILDERDISABLENOTHING
LOC_CQUI_LENSES_BUILDERDISABLENOTHING_TOOLTIP
LOC_CQUI_REMOVE_HERESY
LOC_CQUI_REST_HEAL
LOC_CQUI_SPREAD_RELIGION

**Comment by Akionka** [comment]
I changed every Row node by Replace in _Assets\Text\cqui_text_settings_ru.xml_ and everything (that is translated, Units and Trader Screen tabs for example) works perfectly fine. I am new to Civ VI and Civ VI modding, so I am not quite sure how this works.

**Comment by Akionka** [comment]
Also I checked logs when nodes are _Row_ and here what I got:
_Database.log_:
```
[1631001.043] [Localization] ERROR: UNIQUE constraint failed: LocalizedText.Language, LocalizedText.Tag
[1631001.043] [Localization]: While executing - 'insert into LocalizedText('Tag', 'Language', 'Text') values (?, ?, ?);'
[1631001.043] [Localization]: In XMLSerializer while inserting row into table insert into LocalizedText('Tag', 'Language', 'Text') with  values (LOC_CQUI_LENSES_AUTOAPPLYARCHAEOLOGISTLENS_TOOLTIP, en_US, Автоприменение линзы археолога когда выбран археолог., ).
[1631001.043] [Localization]: In XMLSerializer while updating table LocalizedText from file cqui_text_settings_ru.xml.
[1631001.043] [Localization] ERROR: UNIQUE constraint failed: LocalizedText.Language, LocalizedText.Tag
```
_Modding.log_:
```
[1631001.042] LocalizedText - Loading Assets/Text/cqui_text_settings_ru.xml
[1631001.043] Error parsing C:/Users/Akionka/Documents/My Games/Sid Meier's Civilization VI (Epic)/Mods/CQUI_Community-Edition/Assets/Text/cqui_text_settings_ru.xml
[1631001.043] Warning: LocalizedText - Failed loading XML.
```
And there are not such messages when nodes are _Replace_, so it seems like a solution for me.

**Comment by Akionka** [comment]
I researched the problem a little, it turned out that I just forgot to change the _Language_ tag when translating the mod. I apologize for bothering you for no particular reason. Soon I will do a PR with translations.

**Comment by the-m4a** [comment]
no worries! and sounds good
