### ISSUE TITLE
Civ6 Main Menu, 'Options' not working

### ISSUE THREAD

**Issue by RustyD** [civfanatics/CQUI_Community-Edition#307]
I have pulled the latest main branch (post PR #305  merge) and am testing on Linux. When I try and activate the standard Civ6 Options (off of the standard Civ6 'Main/Save/Load' menu), the screen slightly fades but no options menu is presented. Hitting 'ESC' returns me to the game.

**Comment by the-m4a** [comment]
I would guess it's the goofiness with the filename casing in Linux again.  My Linux install is jacked up at the moment so I can't check, so if you'd be willing to try:

Test 1:
- Rename the file found in (YourCQUIModRoot)/Assets/UI/Options.xml  to options.xml  (make the filename all lowercase)
- In the CQUI.modinfo file, find the two instances of Options.xml (line 157 and 1370) and rename to make that leading "O" lowercase

If that doesn't work, Test 2:
- Rename (YourCQUIModRoot)/Assets/UI/Options_CQUI.lua  to options_cqui.lua
- In the CQUI.modinfo file, find the three instances of Options_CQUI.lua and make all lowercase...

If *that* doesn't work... then I'll see if I can make my Linux install work again

**Comment by RustyD** [comment]
Test 1 seems to fix the issue!

**Comment by the-m4a** [comment]
thanks for doing that!  I'll post a PR today.
