### ISSUE TITLE
Conflict with Leugi's Monopoly++

### ISSUE THREAD

**Issue by Limfjorden** [civfanatics/CQUI_Community-Edition#313]
**Describe the bug**
CQUI seems to conflict with being able to purchase the two new units added by Monopoly++, the investor and the tycoon. AI can use them just fine, but they are unable to be purchased by players. 

**To Reproduce**
1. Enable all Leugi's Monopoly++ mods
2. Enable CQUI
3. Watch as you are unable to purchase investors and later tycoons, while the AI builds all the monopolies and industries.

**Expected behavior**
Being able to purchase investors and tycoons.

**General informations**
 - OS: macOS Mojave
 - Version 1.0.12.9
 - Expansion: All
 - Other mods: All of Leugi's Monopoly++ mods

**Comment by the-m4a** [comment]
heh, actually saw the comments on the Monopoly++ page before seeing this issue here.  I found the problem and will be creating a PR in a few minutes.  Thank you for reporting this!

**Comment by the-m4a** [comment]
I saw there was a PR by @HeroOfOlympus after I had made the changes that is now PR #316 

![image](https://user-images.githubusercontent.com/8787640/120884931-edc9e880-c59a-11eb-852b-afd380784766.png)

**Comment by the-m4a** [comment]
this is fixed now
