### ISSUE TITLE
Investigate: City States new to Maya/Columbia show non-English text

### ISSUE THREAD

**Issue by the-m4a** [civfanatics/CQUI_Community-Edition#32]
Investigate whether this is an issue with CQUI or with the game itself:

https://user-images.githubusercontent.com/8787640/83595543-23b33780-a517-11ea-9e86-c67dc84a0516.png

This appears to affect only the new city states that were added with the Maya/Columbia pack.  Does not appear to occur with the existing city states; unsure if it happens with the renamed city-states (like whatever Palenque got renamed to).

**Comment by Infixo** [comment]
I don't recall anything "Sioux" in the vanilla game. It looks like a mod.

**Comment by the-m4a** [comment]
Hmm... perhaps.  I did see it with a few other City States though, all of them the newer ones.   Good call, though, will check that out.

**Comment by the-m4a** [comment]
I haven't seen this one in a bit.  Likely another mod conflicting.  Closing.
