### ISSUE TITLE
I don't see the LENS and ICON when I select WORKER / BUILDER. I think the settings are incorrect, where should I fix them?

### ISSUE THREAD

**Issue by Alphaz1el** [civfanatics/CQUI_Community-Edition#331]
**Describe the bug**
I don't see the LENS and ICON when I select WORKER / BUILDER.
I think the settings are incorrect, where should I fix them?

**Screenshots**
https://steamcommunity.com/sharedfiles/filedetails/?id=2648069992
https://steamcommunity.com/sharedfiles/filedetails/?id=2648070019

**Comment by Alphaz1el** [comment]
When I removed another mod [More Lenses](https://steamcommunity.com/sharedfiles/filedetails/?id=871712879), it was displayed normally. Sorry about i
![289070_20211107122130_1](https://user-images.githubusercontent.com/25542021/140631303-930e3c4d-1ffc-4276-a569-9b18b040eec3.png)
t.

**Comment by the-m4a** [comment]
yep, cqui includes morelenses so there'd be a conflict there
