### ISSUE TITLE
City Project panel fails to open

### ISSUE THREAD

**Issue by IceLancerSR** [civfanatics/CQUI_Community-Edition#343]
Open city panel , select project. 
Close.
Try to open again and it wont open any more.
This is the log

```
CityPanel: DL_CityPanel Loading CityPanel_Expansion1.lua as base file
Runtime Error: bad argument #1 to 'func' (function expected, got nil)
stack traceback:
	[C]: in function 'func'
	D:\My Documents\My Games\Sid Meier's Civilization VI\Mods\Harmony in Diversity\UI\Replacement\DL_CityPanel.lua:128: in function 'LateInitialize'
	D:\My Documents\My Games\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition-main\Assets\UI\Panels\CityPanel.lua:1256: in function 'OnInit'
Lua callstack:
UnitPanel: DL Loading UnitPanel_Expansion2.lua as base file
```

**Comment by IceLancerSR** [comment]
Is it a clash between two mods? Both using same function?

**Comment by IceLancerSR** [comment]
Addendum. Yup everything works fine once i removed Harmony in Diversity.

**Comment by jav-12** [comment]
I have the same issue. Any fix to use both mods? @IceLancerSR

**Comment by IceLancerSR** [comment]
> I have the same issue. Any fix to use both mods? @IceLancerSR

I gave up on harmony, mod wants to do too much , while not doing anything better then separate mods.

Atm:
its clashing with (from confirmed mods)
civilizations expanded
CIVITAS City-States Expanded
CQUI
Sukritact's civs all of them
Real strategy
Golden age - brave new world
Ditched harmony and took all from list

**Comment by Infixo** [comment]
Not an issue with CQUI. I am closing this.
