### ISSUE TITLE
Trade Route Panel wont open when using CQUI along with BBG

### ISSUE THREAD

**Issue by Gnightz** [civfanatics/CQUI_Community-Edition#344]
**Context**
Hi there! 
I often play alone with both [BBG](https://steamcommunity.com/sharedfiles/filedetails/?id=2865001760) and CQUI enabled.  I don't know if you care about not conflicting with some other frequently used mods, but here i describe a conflict that can be solved by modifying a bit the load order. 

**Describe the bug**
If using CQUI along with [BBG](https://steamcommunity.com/sharedfiles/filedetails/?id=2865001760) ([github](https://steamcommunity.com/sharedfiles/filedetails/?id=2865001760)),  Trade Route Panel wont open.

**Root cause**
This is because both mods overrides tradesupport.lua and BBG override wins, though BBG just do a minor bug fix : 
> [Line 85 and 86](https://github.com/CivilizationVIBetterBalancedGame/BetterBalancedGame/blob/b139ecab70b973122314563cbf5b4df6f16958ac/ui/replacements/TradeSupport.lua#L95) yieldIndex become yieldIndex-1 because of "Firaxis indexing bug C++ indexing starts with 0, while lua starts with 1"

**To Reproduce**
1. Enable [BBG](https://steamcommunity.com/sharedfiles/filedetails/?id=2865001760) (current v5.1.2)
2. Enable [CQUI](https://steamcommunity.com/sharedfiles/filedetails/?id=2865001760) (Workshop update 2021-09-24 3:48)
3. Try the Trade Rroute Panel once you have your first merchant
4. See that nothing happens 

**Expected behavior**
The Trade Route Panel should open

**Suggested solution**
Add an explicit loadOrder of 1 while importing the TradeSupport.lua file. (BBG has no loadOrder for this file, eg 0)

Thank to all contributors!

**Comment by Infixo** [comment]
This bug with indexing has been officialy fixed in the game files approx. 1 month ago. BBG should no longer change this file (if this was the only reason).

**Comment by Gnightz** [comment]
Yes I closed the related PR in February but did not close the issue. 
Thank you !
