### ISSUE TITLE
Always open full tree not working?

### ISSUE THREAD

**Issue by Infixo** [civfanatics/CQUI_Community-Edition#357]
After the recent changes I think the option "always open full tech/civic tree" stopped working. If I click "select tech" on the bottom-right thingy or empty tech in the world tracker it always opens the chooser, not the full tree. Only clicking on the launch bar button opens the full tree.
Can anyone else confirm it?

**Comment by JamieNyanchi** [comment]
Hmm, it seems to still work for me. I just tested it on a new game with the Gathering Storm ruleset. Are you playing with any other ruleset or game modes? Maybe one of my changes conflicts with one of those somehow?

**Comment by Infixo** [comment]
My other mod was clashing. Closing.
