### ISSUE TITLE
Reduce reliance on replacement files

### ISSUE THREAD

**Issue by the-m4a** [civfanatics/CQUI_Community-Edition#37]
Work through the various replacements and wherever possible, convert to the extend-and-replace-functions-only-if-necessary mechanism.

meaning: don't copy entire files into a mod when you don't need to. Replace functions when you have to, but try not to.  (see explanation below in one of my replies if not clear)

I created a branch (ReduceReplacements) for this

Files that we should look at:
**Base\UI**
- ActionPanel.lua (turns out it does have customization)
- ~~CitySupport.lua~~ Done
- ~~InGame.lua~~ Cannot be modified/extended, replace only (see comment in orig file)
- ~~Launchbar.lua~~ Done (in Soothsayer PR)
- SupportFunctions.lua
- TechAndCivicSupport.lua
- ~~WorldInput.lua~~ Done (in Soothsayer PR)
- WorldTracker.lua

**Base\UI\Choosers**
- CivicsChooser.lua
- ResearchChooser.lua

**Base\UI\Instances**
- LeaderIcon.lua

**Base\UI\Panel**
- CityPanel.lua
- CityPanelOverview.lua
- StatusMessagePanel.lua

**Base\UI\PartialScreens**
- CityStates.lua

**Base\UI\Popups**
- GreatPeoplePopup.lua
- PolicyReminderPopup.lua
- TechCivicCompletedPopup.lua

**Base\UI\WorldView**
- CityBannerManager.lua

**Expansion1\CityBanners**
- CityBannerManager.lua

**Expansion1\Replacements**
- CitySupport.lua
- LeaderIcon.lua
- CityPanelCulture_CQUI.lua (rename file only to be consistent with other files)
- CityPanelOverview_expansion1_CQUI.lua (rename only to be consistent)
- WorldTracker_expansion1.lua (rename to be consistent)

**Expansion2\CityBanners**
- CityBannerManager.lua

**Expansion2\Replacements**
- Citypaneloverview_expansion2_CQUI.lua (rename for consistency)
- ~~CitySupport.lua~~ Done
- ~~InGame.lua~~ Cannot be modified/extended, replace only (see comment in orig file)

**Comment by the-m4a** [comment]
Keeping notes (will edit as I go along)
- ActionPanel.lua was same as the version that ships with the game, so it was just removed

**Comment by Infixo** [comment]
What do you mean by "extend-and-replace-functions-only-if-necessary mechanism."

**Comment by the-m4a** [comment]
meaning:  don't copy entire files into a mod when you don't need to.  Replace functions when you have to, but try not to.

Two examples:
CitySupport.lua has this monster-sized function GetCityData, where the change in CQUI is to get 5 additional fields that are used in the banner.  Instead of replacing that entire function, we could call the base function and then just add the stuff we needed to the table at the end because lua doesn't care about array sizes and junk, apparently:

```
function GetCityData( pCity:table )
  -- call the base function, extend the return data we give back
  local data = BASE_CQUI_GetCityData(pCity);

  -- Extend the table returned by the base function and return that
  local productionInfo :table = GetCurrentProductionInfoOfCity( pCity, SIZE_PRODUCTION_ICON );
  data["ProductionProgress"] = productionInfo.Progress;
  data["ProductionCost"] = productionInfo.Cost;

  local pCityGrowth :table = pCity:GetGrowth();
  local foodSurplus :number = pCityGrowth:GetFoodSurplus();

  data.["CurrentFood"] =  pCityGrowth:GetFood();
  data.["RequiredFood"] = pCityGrowth:GetGrowthThreshold();
  data.["FoodGainNextTurn"] = foodSurplus * pCityGrowth:GetOverallGrowthModifier();

  return data;
end
```

In Ingame.lua, there's an entire function that needs to be replaced because there's no way to extend it.  This is the DefaultMessageHandler for KeyUp, with a function defined in-line.  Azurency added a change there, so the entire function is overwritten.  In this case I called out the CQUI custom code:
```
DefaultMessageHandler[KeyEvents.KeyUp] =
  function( pInputStruct:table )

    local uiKey = pInputStruct:GetKey();

    if( uiKey == Keys.VK_ESCAPE ) then
-- ==== CQUI CUSTOMIZATION BEGIN  ==================================================================================== --
      -- AZURENCY : if a unit or a city is selected, deselect and reset interface mode
      -- instead of showing the option menu immediatly
      if (UI.GetHeadSelectedCity() or UI.GetHeadSelectedUnit()) then
        UI.DeselectAll();
        UI.SetInterfaceMode(InterfaceModeTypes.SELECTION);
        return true;
      end
-- ==== CQUI CUSTOMIZATION END ==================================================================================== --
      if( Controls.TopOptionsMenu:IsHidden() ) then
        OpenInGameOptionsMenu();
        return true;
      end

      return false;	-- Already open, let it handle it.
    elseif( uiKey == Keys.B and pInputStruct:IsShiftDown() and pInputStruct:IsAltDown() and (not UI.IsFinalRelease()) ) then
      -- DEBUG: Force unhiding
      local msg:string =  "***PLAYER Force Bulk unhiding SHIFT+ALT+B ***";
      UI.DataError(msg);
      m_bulkHideTracker = 1;
      BulkHide(false, msg);

    elseif( uiKey == Keys.J and pInputStruct:IsShiftDown() and pInputStruct:IsAltDown() and (not UI.IsFinalRelease()) ) then
      if m_bulkHideTracker < 1 then
        BulkHide(true,  "Forced" );
      else
        BulkHide(false, "Forced" );
      end
    end

    return false;
  end
```

**Comment by Infixo** [comment]
Ok, got it.
That 2nd example you can also make as an extension.
main.lua
FunTable[a] = functionX(params) {}

ext.lua

basefun = FunTable[a]
functionXext(params){
basefun(params);
your code}

FunTable[a] = functionXext

**Comment by the-m4a** [comment]
ah good point!  I will try that out

**Comment by the-m4a** [comment]
@alimulhuda I saw the next patch is due out on June 25th - all of the current files are checked in to the UIFiles repo, right?  (I believe they are, just confirming for 100% certainty)
