### ISSUE TITLE
Show Luxuries option is not honored if set in cqui_settings_local.sql

### ISSUE THREAD

**Issue by the-m4a** [civfanatics/CQUI_Community-Edition#44]
Example from cqui_settings_local.sql:
```
INSERT OR REPLACE INTO CQUI_Settings -- Don't touch this line!
  VALUES
      ("CQUI_AutoExpandUnitActions", 0),
      ("CQUI_ProductionQueue", 1),
      ("CQUI_ShowLuxuries", 0),
      ("CQUI_Smartbanner_Districts", 0),
      ("CQUI_TechPopupVisual", 0),
      ("CQUI_TechPopupAudio", 0),
      ("CQUI_WonderBuiltPopupVisual", 0),
      ("CQUI_WonderBuiltPopupAudio", 0),
      ("CQUI_ToggleYieldsOnLoad", 0);
```

When starting a new game, a look at the options will show the CQUI_ShowLuxuries as unchecked.
![image](https://user-images.githubusercontent.com/8787640/84954358-187d1180-b0aa-11ea-863d-fa13197fbcf2.png)

Once a setting is changed in the CQUI Options Menu (even if that setting is NOT the Show Luxuries), the option will be honored and the luxuries will no longer appear in the top panel.

The way this is implemented makes me think something else is wrong and this may not be the only setting affected by this.

**Comment by the-m4a** [comment]
this could be a matter of forcing the _CQUI_OnSettingsUpdate_ to be called from the script Initialize function, as right now all that does is set up the LuaEvents hook

```
LuaEvents.CQUI_SettingsUpdate.Add(CQUI_OnSettingsUpdate);
```
which AFAIK doesn't result in the function being called

```
function CQUI_OnSettingsUpdate()
  CQUI_showLuxury = GameConfiguration.GetValue("CQUI_ShowLuxuries");
  RefreshResources();
end
```

**Comment by Infixo** [comment]
The problem is that CQUI_showLuxury as initialized as true, so until Update is called, resources will always be shown. What is missing is a hook to CQUI_SettingsInitialized() to set it correctly.
I will fix, also to see how the merge process works.
