### ISSUE TITLE
Bug (?) with Environment Skin and Tactical Camera mods

### ISSUE THREAD

**Issue by paveldesigner** [civfanatics/CQUI_Community-Edition#45]
**Describe the bug**
Hello! I found a bug. Some kind of conflict with the mods Environment Skin and Tactical Camera. After loading the save game, these mods do not work.
Sorry for my english :)
Environment Skin: Sid Meier's Civilization V https://steamcommunity.com/sharedfiles/filedetails/?id=1702339134
Tactical Camera by Tom Illar https://steamcommunity.com/sharedfiles/filedetails/?id=871412359

**To Reproduce**
1. Starting a new game with CQUI
2. I'm playing
3. I save the game and exit the game.
4. Then, load the save.
5. The game works, but I can’t zoom out the camera (Tactical Camera does this) and the visual of the game becomes normal for CivVI (Environment Skin should change the visual).

It is possible to play, but these two modes do not work. If i disable CQUI, then the mods work again.
I tried disabling ALL other mods and I’m sure that the reason is in CQUI.

**General informations**
 - OS: Win10 1909
 - Version of the CIV VI: 1.0.1.501 (504666)
 - Expansions: ALL exept New Frontier Pass
 - Other mods: a lot of mods, but i tried to disable all of them.

**Logs**
Whole Logs folder https://yadi.sk/d/m9xdaeJpYxDAwg

**Comment by Infixo** [comment]
The camera mod is literally a single camera.artdef file. No DB, no Lua, no xml, nothing but this artdef. And in CQUI the only .artdef is for Minimap. CivV mod has a few artdefs but they are all for different subsystems. There is no conflict here imo.
There are also no meaningful errors in any log.
I followed your steps and everything works ok for me. Both camera mod and skin mod are working good after the reload, both for a new game or some old ones.
