### ISSUE TITLE
consider creating a reusable library/mod with basic Civ6 game calculations

### ISSUE THREAD

**Issue by alexeyOnGitHub** [civfanatics/CQUI_Community-Edition#48]
I noticed that at least some Civ6 plugins (like CQUI and others) have their own methods to calculate basic things like housing and such. while ideally I would want the UI-level plugins to focus on UI and just use the calculating functions from the base game, I understand that sometimes it is not possible due to the base game source code being closed (please correct me if I am wrong).

now, if we do have to re-implement the basic game calculations in a plugin, can we extract this into a reusable library (a separate mod?) that other mods can include or depend on? not sure if Steam Workshop supports mods dependencies, but having this code in one place would hopefully greatly simplify its maintenance. developers working on various mods/plugins (not just CQUI) could hopefully import this reusable library into their UI-level plugins.

e.g. the same "how much housing" function can be used in all kinds of UI plugins.

again, ideally this should be available in the base game's API, but if it is not, we can benefit from creating the "base game API" ourselves.

tagging @alimulhuda @the-m4a

**Comment by the-m4a** [comment]
yes, this would be great - if nothing else we pack these kinds of things into a single or small group of files that, worst case, can be used as-is by other mods should it be needed.  Which would also allow for packing them into their own mod, if needed.

**Comment by Infixo** [comment]
CQUICommon.lua
I will do some cleanup there.
