### ISSUE TITLE
Setup.exe

### ISSUE THREAD

**Issue by onleeking** [civfanatics/CQUI_Community-Edition#50]
I would also like you to make an application for setting up the mod. Very inconvenient to customize in a text document. Make a graphical application in which you can configure everything that is in "cqui_settings.sql". Informative and understandable, since 0 and 1 are not clear to everyone

**Comment by alexeyOnGitHub** [comment]
whatever user settings are available for configuration should be presented in the Game UI itself (CQUI settings panel). creating an additional application to configure these things outside of the game won't have much value
