### ISSUE TITLE
Mouse over is not working correctly on city banner

### ISSUE THREAD

**Issue by wayneb64** [civfanatics/CQUI_Community-Edition#53]
If you open the city panel, the worker hexes are colored green/red to indicate locked or not. This coloring is not shown outside the city view on mouse over (unless you open/close the city first). Clicking a unit breaks it again.

**Screenshots**

**General informations**
Win 10
 - Version [e.g. 1.0.0.256]
Latest Civ (all DLCs except this years new ones)
 - Expansion [e.g. None, Rise and Fall]
All
 - Other mods [e.g. YnAMP]
Free Walls for City States, Constant Brightness (forget the name)

**Save game and logs**
Please attach if you can your save game and the logs. You can find them in `..\documents\my games\sid meier's civilization vi\` on windows or `/Users/[user]/Library/Application Support/Sid Meier's Civilization VI/` on Mac OS.

**Additional context**
This has been mentioned in discussions but no issue was open.

**Comment by wayneb64** [comment]
EDIT: Actually this is how it behaves in my pre-2020 version so this is not a regression. Not sure if the behavior is a bug or not at this point.

**Comment by Infixo** [comment]
I am confused.
1. Mouse hover, When you mouse hover over a banner then some hexes are colored and it also shows the culture border growth.
2. City view. When you enter the city view, then you see the same coloring plus citizen icons, buy next tile, etc.
What's the issue?

**Comment by wayneb64** [comment]
The 'feature' I am talking about is in the city view it shows locked and unlocked citizens by coloring the tiles green or red. When you are outside the city view if you mouse over the banner that same feature shows on the map. This only works after just leaving the city. If you focus a unit then hover does nothing until you enter a city and exit. Then again you can mouse over cities to see where unlocked workers are. I think it always shows the worker icons but I find them a little harder to see. Make sense?

**Comment by Infixo** [comment]
Yup, much more sense :)
However from what I see in the game, you don't need to go into the city view again. Just unselect a unit. This is how it works for me (xp2 ruleset).
So, it boils down to the following: when you mouse hover then 3 things are displayed (yields, colors, border) but when a unit is selected then only 2 things are displayed (yields and border). Colors are missing.
I assume atm that city view is ok, no problems there.

**Comment by Infixo** [comment]
I checked the code and it seems that this is not a bug but actually a fix for a problem with lenses. There is a comment from authors:
    -- Fix for lens being shown when other lenses are on.
    -- Don't show this lens if any unit is selected.
    -- This prevents the need to check if every lens is on or not, like builder, religious lens.
I suppose it is like this because those color are actually handled by More Lenses mod, not CQUI itself. CQUI adds yielda and border growth and they don't interfere with lenses. However, if a unit is selected (builder, religion, scout, etc.), a lens can be put on and it clearly conflicts with the citizen mgmt colors.

**Comment by Infixo** [comment]
The root cause of the problem is that there are approx. 60 lens layers and the only function that checks which are active is UILens.IsLensActive() and it requires a specific layer id. If there was a function IsAnyLensActive() then this could be used instead of checking if a unit is selected.

**Comment by wayneb64** [comment]
Un-focusing the unit works and now that I know that it's not worth 'fixing' this it sounds like. Closing this.
