### ISSUE TITLE
Relocate the City Range Strike button?

### ISSUE THREAD

**Issue by the-m4a** [civfanatics/CQUI_Community-Edition#55]
City Range Strike button can get hidden sometimes and it's easy enough to relocate dynamically
Before:
![image](https://user-images.githubusercontent.com/8787640/85651456-eeed5880-b65c-11ea-8415-72fef55a90af.png)

After:
![image](https://user-images.githubusercontent.com/8787640/85651876-0bd65b80-b65e-11ea-9d45-59b4494d0847.png)

Code to do this:
**Basegame**
```
BASE_CQUI_CityBanner_UpdateRangeStrike = CityBanner.UpdateRangeStrike;
function CityBanner.UpdateRangeStrike(self)
    -- Move the CityStrike icon and button to the top of the City bar; similar to the Sukritact Simple UI Mod (which puts it on the right)
    BASE_CQUI_CityBanner_UpdateRangeStrike(self);

    local cityBanner = self.m_Instance;
    if (cityBanner == nil) then
        return;
    end

    if (self.m_Type == BANNERTYPE_CITY_CENTER) then
        -- The standard icon has an "attachment" piece that looks like it hangs down from the City Banner
        -- Rotating it makes it look like it's attached to the part above
        -- TODO: Make this configurable?  (Where if not set, it just uses the standard location)
        cityBanner.CityAttackContainer:Rotate(180);
        cityBanner.CityAttackContainer:SetSizeVal(36,45);
        cityBanner.CityAttackContainer:SetAnchor("C,T");
        cityBanner.CityAttackContainer:SetOffsetVal(0,10);
    end
end
```

**Expansions**
```
BASE_CQUI_CityBanner_UpdateRangeStrike = CityBanner.UpdateRangeStrike;
function CityBanner.UpdateRangeStrike(self)
    -- Move the CityStrike icon and button to the top of the City bar; similar to the Sukritact Simple UI Mod (which puts it on the right)
    BASE_CQUI_CityBanner_UpdateRangeStrike(self);

    local cityBanner = self.m_Instance;
    if (cityBanner == nil) then
        return;
    end

    if (self.m_Type == BANNERTYPE_CITY_CENTER) then
        -- The standard icon has an "attachment" piece that looks like it hangs down from the City Banner
        -- Rotating it makes it look like it's attached to the part above
        cityBanner.CityStrike:Rotate(180);
        cityBanner.CityStrike:SetSizeVal(36,45);
        cityBanner.CityStrike:SetAnchor("C,T");
        cityBanner.CityStrike:SetOffsetVal(0,10);

        cityBanner.CityStrikeButton:SetAnchor("C,C");
        cityBanner.CityStrikeButton:SetOffsetVal(0,0);
    end
end
```

**Comment by Infixo** [comment]
Why do you even wanna code this functionality in Lua? This is a control defined in .xml, so you can place it wherever you want just by changing .xml.  Maybe with some Lua adjustment, because there is an extra bar for walls. But probably can be self-adjusting by using <Stack>. Tricky, but possible.
Sukritact is using Lua because he doesn't want to change .xml as it cannot be done in any other way but by copying entire file and changing what you want. CQUI has its own copy and overwrites the base file anyway, so it should be easier to do it via .xml and (maybe) a bit of Lua.

**Comment by the-m4a** [comment]
I am not married to making the change in Lua, just saw what Sukritact did and saw that the changes were easy enough to make in Lua that it is a possibility.  When I was cleaning up the code for the Seastead / CityBannerManager changes last night, I needed to stash this somewhere and creating this issue was that somewhere.

I'm happy to do the changes either way - the XML is probably the better way as it's the generally accepted method for repositioning objects around.  Doing it in Lua could mean not replacing the XML, however, I think that XML is replaced in the mod already, so...

**Comment by alexeyOnGitHub** [comment]
I am fine with the XML approach. another thing that I find inconvenient with the city range attacks is that the red circle is pretty small and it takes extra time to select it. maybe increase its size? and also support `r` hotkey for the currently selected city to perform its range attack / bombardment.
