### ISSUE TITLE
Reformat - 4 spaces, not 2.

### ISSUE THREAD

**Issue by the-m4a** [civfanatics/CQUI_Community-Edition#56]
After sticking with the 4-spaces instead of 2 in the CityBannerManager changes, it became very clear to me that it makes a significant difference in terms of my readability.  There was a significant amount of shifting around code, and in spite of things where multiple nested if statements required a wide monitor, the experience was much better.

I'm happy to start clicking through and updating some of these, and intend to do so once the Seasteads issue is done and we figure the other remaining issues (like the Settings being applied properly, and whatever comes from today's update from Firaxis).

Changes for this issue should be in formatting only - **no logic changes**.  If we see changes to the logic that should happen, we should open an issue and track it.

**Comment by alexeyOnGitHub** [comment]
if you think 4 spaces make more sense, let's reformat in a separate commit. also update the contributing guidelines file accordingly

**Comment by the-m4a** [comment]
yeah - it'd be in separate PRs and whatnot... that one I'm pushing now though, that's all new files, the original files were deleted, so there's nothing that's a strict format change
(I guess if you count cut/paste of the code from one to the other... however things are re-ordered and whatnot so it's not easy to get a side-by-side comparison)

**Comment by the-m4a** [comment]
I started work on this last night once I pushed the other changes in the seasteads branch.  Will only be fixing spacing issues so it should be a rubber stamp

**Comment by alimulhuda** [comment]
One observation from what the unmodded files follow. They seem to be using 2 spaces for XML files and 4 spaces for LUA. Probably because XML files can get very deep indentations.
Just wanted to leave this note in case you are planning on changing everything to 4 spaces, then for future reviews for new XML code we just have to pay attention to anything that uses the unmodded files as a base.

**Comment by the-m4a** [comment]
some of those XML files are a mess.  I've updated some of them (using an online formatting tool), and I prefer the consistent formatted look to the inconsistency from Firaxis...

For example - while this may be because I have VSCode set to always use _the size of 4 spaces_ for the tab character - here's a file from Firaxis, untouched by us as far as I know, where some lines are using tabs and others are using spaces

![image](https://user-images.githubusercontent.com/8787640/86312036-96770780-bbd6-11ea-8bba-4d5df3c3b9c1.png)

When they're using the actual space character, it's 2.  But since I tell VSCode to set the width of the tab character to 4 spaces, you get this file that looks like someone dropped it.

Site I use is -- https://www.freeformatter.com/xml-formatter.html#ad-output
There are a few times where the Game XML has attributes declared multiple times, which I suppose it handles, but the formatter does not like.  I will go temporarily rename the offending attributes to get the formatting and then restore the names

**Comment by alimulhuda** [comment]
By the way did you try using the code formatting feature for VSCode. Found this link https://stackoverflow.com/questions/29973357/how-do-you-format-code-in-visual-studio-code-vscode. Tried it with the "XML Tools" extension by Josh Johnson then it can format the document with Alt+Shift+F.

**Comment by the-m4a** [comment]
the XML formatter extension is nice!  thanks for the tip

I took a peek yesterday at the diffs created here on Github - it's terrible whenever I add extra blank lines, so I have been going through and removing any extra blank lines so the diffs line up and we can clearly see spaces are the only differences in the files
