### ISSUE TITLE
Number of followers in the religion banner 

### ISSUE THREAD

**Issue by Infixo** [civfanatics/CQUI_Community-Edition#59]
Religion banner shows only religion icons which is totally not helpful and forces you to click on it to open the enhanced version.
This enhancement simply adds num of followers and pressure info in the tooltip, so whenever a Religion Lens is activated, it can be easily seen at once what is happening in all visible cities. No need to click anything.

![religionbanner](https://user-images.githubusercontent.com/25866684/85953786-16049c80-b973-11ea-900a-f54a2e465db2.jpg)

A small modification of the city banner in needed, so I will upload this once #49 is pulled in.

**Comment by the-m4a** [comment]
Looks good on basegame too, nice work!
![image](https://user-images.githubusercontent.com/8787640/86487803-f626fd00-bd13-11ea-8d34-9b9c0a992dcb.png)
