### ISSUE TITLE
Consider (Re)Integration of Better Report Screens

### ISSUE THREAD

**Issue by the-m4a** [civfanatics/CQUI_Community-Edition#6]
**Is your feature request related to a problem? Please describe.**
CQUI once had the Unit Report Screen integrated, though this is no longer the case.  The mod "Better Report Screen" released to Steam Workshop by infixo is the updated version of URS, and works nicely alongside CQUI.   

**Describe the solution you'd like**
Integrating this into CQUI once again would be a nice thing, with the current author's permission, of course.

**Additional context**
Link to Mod I speak of:
https://steamcommunity.com/sharedfiles/filedetails/?id=1312585482&searchtext=better+report+screen

**Comment by alexeyOnGitHub** [comment]
I agree that having the improved reports would add to user experience. not being able to sort cities by production, or see the improved units panel leads to a suboptimal user experience

**Comment by the-m4a** [comment]
The guy that owns the upload to Steam Workshop said he'd look into it, but I'm not sure if that was a firm commitment or not.  I don't think we've seen him on here to say as much.

**Comment by alimulhuda** [comment]
I think infixo was saying that he would prefer to keep it separate from CQUI but try to maintain compatibility on his end. Given that infixo seems to pretty deep into modding and is keeping the mods updated, my opinion is that we do nothing and just let the mod work alongside CQUI.

I would be more interested in getting this integrated if there was some kind of conflict that prevented using Better Report Screen or if it was not being kept up to date.

**Comment by the-m4a** [comment]
Ah, I misunderstood - and that works as well.  We have enough things to try to keep straight with this one at the moment, and as long as infixo is updating it, then that's fine.

**Comment by Infixo** [comment]
@alimulhuda is correct. I want BRS to be standalone and I will make sure that it will work with CQUI.
-----
As a separate note, I just wanted to say that integrations are not needed in CQUI. Either the mod is standalone and maintained by the author or if the author doesn't wanna do that any more and gives permission to use it - just include it the CQUI code and treat as integral part of the mod.

If you want standalone mods to somehow cooperate with CQUI then there are many ways possible to achieve that. Copying the entire mod to add few lines of code is imho probably the worst of them. The mod gets updated, you need to re-apply the changes, and make sure it still works. It is just unnecessary work.

**Comment by the-m4a** [comment]
Yeah, the more I get into this, that is very much the way to go.  When I made this issue, I wasn't taking into account the work necessary.  We may want to go the other way - take out integrations (like Better Trade Screen?) where we can... and figure out how to coexist with others when necessary

**Comment by alexeyOnGitHub** [comment]
ok, let's close this task then
