### ISSUE TITLE
Compatibility with "City Original Owner" mod (or similar functionality)

### ISSUE THREAD

**Issue by Sorxus** [civfanatics/CQUI_Community-Edition#62]
Information about city original owner is always good one before you conquer some city, so I think good to have installed mod with that name (author is Imhotep: https://steamcommunity.com/sharedfiles/filedetails/?id=2021476879).
There is only one small glitch: both mods aren't totally compatible (but COO is compatible with Sukritact's Simple UI-A). 

So is there any chance to make it compatible or to include that nice functionality in CQUI?

**Comment by Infixo** [comment]
It would probably easier to just add this info to one of city tooltips. City’s original owner is directly available via Lua, so it is like couple of lines of code.

**Comment by Sorxus** [comment]
That would be good addition...

**Comment by Infixo** [comment]
It is only implemented for expansions. Base game doesn't have the "owner info" functionality in the first place, so there is nothing to work on.
