### ISSUE TITLE
Fix casing for DiplomacyActionView loads with Exp1

### ISSUE THREAD

**Issue by the-m4a** [civfanatics/CQUI_Community-Edition#68]
The diplomacyactionview_CQUI_expansion1.lua file and diplomacyribbon_CQUI_expansion1 file use Camel casing for the "include" statements to load the CQUI game files

update the casing to match how they appear in the file system, as it likely affects Linux

**Comment by Infixo** [comment]
There are several instances of:
include("Civ6Common");
and the file is civ6common.lua.
Can you also fix that quickly?

**Comment by Infixo** [comment]
Actually, it is better to remove this file. As the comment says:
--  CQUI: The ONLY change to this file from the base version (besides this comment) is the include("CQUICommon") declaration below
And it is true, I just checked.
Basically add where necessary cquicommon (also lowercase it, just in case) and make it this "common functions stuff" from another issue.
