### ISSUE TITLE
Consider Restoring Show/Hide WorldTracker button functionality

### ISSUE THREAD

**Issue by the-m4a** [civfanatics/CQUI_Community-Edition#7]
**Describe the bug**
The small circular button to the right of the Science/Culture/Government/Climate does not appear to do anything of use.  In reality it is opening a context menu, but that menu is currently empty... so it does not do anything of use.

![image](https://user-images.githubusercontent.com/8787640/83373242-81f7e300-a37c-11ea-8533-b2d385d3a531.png)

In Vanilla, this button hides the World Tracker.

**To Reproduce**
1. Click on the button circled in picture above.
2. Observe the appearance (or disappearance) of a line below that button.
![image](https://user-images.githubusercontent.com/8787640/83373332-cf745000-a37c-11ea-9aee-72e6ddc0bcea.png)

**Expected behavior**
  We should consider restoring this functionality, or at least providing a menu option that allows the user to restore this functionality.

**General informations**
 - OS: Win10
 - Version 1.0.1.501 (Spring 2020 Patch)

**Comment by the-m4a** [comment]
The code that's controlling this is in LaunchBar.lua, and probably in LaunchBar.xml (as it removes the arrow that occupies the center of that button that is observed in Vanilla).

This is also a copy of a report from https://github.com/Azurency/CQUI_Community-Edition/issues/14

**Comment by therealcrow999** [comment]
Yeah from what I remember it was removed when Modular Screen mod was added back when Chaorace added it in. I think this is info on it:
https://github.com/Azurency/CQUI_Community-Edition/commit/571f7af91be6d71980dde2dd4967859bfda94222

**Comment by therealcrow999** [comment]
I would try to contact astog and see if he can help. I think he is still around, he does the More Lenses, mod.

**Comment by alexeyOnGitHub** [comment]
@therealcrow999 would you be able to submit a PR or drive this to ensure someone else submits a PR with the fix?

**Comment by Infixo** [comment]
I'll try to implement something like this:
- Left Click - original functionality, i.e. open / close world tracker
- Right Click - open / close extras

**Comment by Infixo** [comment]
I've restored the default "toggle world tracker" button and its functionality.
If there are no extras, then this is it - the extra button will be hidden.
If someone will use the extras then the button will appear above the world tracker and will function as in CQUI.

**Comment by wayneb64** [comment]
Stupid question, what exactly is a "World Tracker"? I have tried to google it but no luck.

**Comment by Infixo** [comment]
There can be more sections added fairly easily. I suppose Firaxis had some bigger plans for it, but it ended up with only tech and civics trackers.
