### ISSUE TITLE
Minor XML typos

### ISSUE THREAD

**Issue by the-m4a** [civfanatics/CQUI_Community-Edition#77]
I've noticed a couple of typos in XMLs that I'm not sure how they do not break things, but they should probably be fixed

Maybe the game has some logic built in to deal with invalid characters in the XML?

base\CityPanelOverview.xml:  There is an extra > character on line 282.  As best I can tell this is in the actual released code, so this showing up in CQUI is just because the file was copied over

base\CityPanel.xml: Invalid tag at the end of the file (has </Grid>, should be </GridButton>).  This issue has existed for about 2 years - Azurency introduced this with the "Update for 1.0.0.229" checkin about 2 years ago.

exp2DiplomacyActionView:  There's a mysterious trailing 'y' on line 518.  It exists as far back as I can find it in the CQUI Github history.  It apparently also exists in the basegame unmodified version.  Weird.

**Comment by Infixo** [comment]
XML is quite resilient, so ex. for Grid tag those were harmless I suppose.
