### ISSUE TITLE
Provide Download for Civ6 from Epic Store

### ISSUE THREAD

**Issue by pmwmedia** [civfanatics/CQUI_Community-Edition#8]
Could you provide the ZIP file of the mod for downloading for Civilization 6 from Epic Store?

**Comment by the-m4a** [comment]
Not sure what you mean?  Can the mod be published to their store (as a zip)or you asking for a zip download?
If you go to the main page for the source file repo - https://github.com/civfanatics/cqui_community-edition - there is a clone button which should also have a download as zip, which contains all the files.  The readme contains direction on where to unzip it. 
(If you’re not familiar - the mod is a series of xml, lua, and sql files - nothing to compile, etc.  just place somewhere that Civ6 can see the modinfo file and you should be good to go)

**Comment by pmwmedia** [comment]
Thank you! I will download the mod as you have described :)

**Comment by pmwmedia** [comment]
Works perfectly with the latest version from Epic Store.

@the-m4a: Thank you very much for your great work!
