### ISSUE TITLE
cqui_settings_local is being overwritten by the workshop updates

### ISSUE THREAD

**Issue by wayneb64** [civfanatics/CQUI_Community-Edition#84]
I recently used my test PC to tryout the latest CQUI and everything seemed fine for the short time I tested it. I went to look at the files today to see if it had gotten an update and sure enough yesterday some later files where there.

Unfortunately my cqui_settings_local.sql file got overwritten, defeating the point of the file. Should it really be in the release?

This was on Win 10 with expansion 1 and 2.

**Comment by the-m4a** [comment]
Crud, I must've included it in the release when I last uploaded it.  I apologize for that.  I'll delete it and push a new release now.

**Comment by the-m4a** [comment]
@wayneb64 Can you verify this is no longer a problem?

**Comment by wayneb64** [comment]
Well now I see files dated 7/8/2020 but NO cqui_settings_local.sql file in my Assets folder. I copied my file their again but it seems like the update wiped out my file. I know this has not been an issue in the past, does the Mod look under 

(steam install folder)
H:\SteamLibrary\steamapps\workshop\content\289070\2115302648\Assets

or

(Documents folder)
C:\Users\---\Documents\My Games\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition-expansion2\Assets

**Comment by the-m4a** [comment]
I think it would look under the first one - to my knowledge there isn’t a way to direct it to the other location if it came from the steam workshop.  Are you certain it did not overwrite previously?  I had the file in my local directory and pushed updates in the past - this time I deleted my copy first and pushed the update...

**Comment by wayneb64** [comment]
Maybe it used to overwrite it as we didn't get updates very often in the past but even so why did it delete my file that I had put there on 7/5? Does it wipe the directory every time there is an update?

**Comment by the-m4a** [comment]
I think it does, which is a firaxis thing as far as I know.  And true on the more updates lately... been fixing things.  And just sent one out now, which means it wiped again :/

**Comment by wayneb64** [comment]
So let me ask a different question, how can this be fixed so that there can be a 'safe' copy of this file that doesn't get wiped out? Or is there a better way to preserve the user's preferences and not have to set them all up again every game?

**Comment by the-m4a** [comment]
I would love for there to be a better way to preserve the preferences.  I'm not sure if there _is_ a way.  No idea.  I would also like to have it fixed.

**Comment by Infixo** [comment]
> I think it does, which is a firaxis thing as far as I know.
How is steam workshop update process a “firaxis thing”?

For any mod from Steam that I want to do some changes, I do a local copy. I wasn’t aware that it also deleting extra files, so like a clean and reload all. Never needed that.
For CQUi, since I am also a dev, I just take it directly from github, no issues here.

Technically there is a mechanism to store user preferences - well, most of normal game options are stored this way. I wanted to use it in one of my mods but it requires changes to FrontEnd UI files and it is actually pretty complex.

**Comment by wayneb64** [comment]
Would it be possible to look for the cqui_local_settings file under USER/Documents somewhere instead of in the workshop folder? This would prevent it being overwritten. I am still seeing an 'empty' cqui_local_settings file showing up with the latest update date/time.

**Comment by Infixo** [comment]
@wayneb64 Not possible. All mod files are referenced to the place where .modinfo is located.

Why don’t you just make a copy of your local settings and keep it locally? Then when the mod is updated, just copy it again. Imo, that’s the simplest way atm. There been a few changes recently, but eventually it’s gonna stop and the updates will be like weekly or biweekly.

**Comment by wayneb64** [comment]
That's what I have been doing but it's kind of a hassle to remember as I think I have to have it there before I start a new game right? If the file gets nuked mid game do my settings revert or is it only when creating a new game?

**Comment by Infixo** [comment]
This file is needed only when the game starts.
After that the game saves current settings into the savefile and reads from there when reloading.

**Comment by the-m4a** [comment]
this is now worked around by the fact the game will load a cqui_settings_local file from the mod's parent folder, as documented in our wiki
