### ISSUE TITLE
Issues observed during Multiplayer games

### ISSUE THREAD

**Issue by the-m4a** [civfanatics/CQUI_Community-Edition#85]
Per the Report Issues thread on the workshop page, players that are _not_ hosting appear to have trouble.  Need to look into this further.

Logs snippet on machines that have trouble:

#1
Runtime Error: E:\games\Steam\steamapps\workshop\content\289070\2115302648\Assets\UI\Panels\CityPanelOverview.lua:122: attempt to index a nil value
stack traceback:
E:\games\Steam\steamapps\workshop\content\289070\2115302648\Assets\UI\Panels\CityPanelOverview.lua:122: in function 'SetDesiredLens'
E:\games\Steam\steamapps\workshop\content\289070\2115302648\Assets\UI\Panels\CityPanelOverview.lua:164: in function 'HideAll'
E:\games\Steam\steamapps\common\Sid Meier's Civilization VI\DLC\Expansion2\UI\Replacements\CityPanelOverview_Expansion1.lua:28: in function 'HideAll'
E:\games\Steam\steamapps\common\Sid Meier's Civilization VI\DLC\Expansion2\UI\Replacements\CityPanelOverview_Expansion2.lua:26: in function 'HideAll'
E:\games\Steam\steamapps\workshop\content\289070\2115302648\Assets\UI\Panels\CityPanelOverview.lua:169: in function 'OnSelectHealthTab'
E:\games\Steam\steamapps\common\Sid Meier's Civilization VI\Base\Assets\UI\TabSupport.lua:176: in function '(anonymous)'
[C]: in function '(anonymous)'

#2
Runtime Error: E:\games\Steam\steamapps\workshop\content\289070\2115302648\Assets\UI\Panels\CityPanel.lua:191: attempt to index a nil value
stack traceback:
E:\games\Steam\steamapps\workshop\content\289070\2115302648\Assets\UI\Panels\CityPanel.lua:191: in function 'CQUI_OnInterfaceModeChanged'
[C]: in function 'func'
[C]: in function '(anonymous)'

**Comment by the-m4a** [comment]
One important aspect - clicking on the City (plot) instead of the banner does not show this issue, only when clicking on the City Banner to bring up the city view...

I found a bug in the OnCityBannerClick code:
``
function OnCityBannerClick( playerID, cityID )
    print_debug("CityBannerManager_CQUI: OnCityBannerClick ENTRY  playerID:"..tostring(playerID).." cityID:"..tostring(cityID));
    BASE_CQUI_OnCityBannerClick(playerID, cityID);

    local pPlayer = Players[playerID];
    if (pPlayer == nil) then
        return;
    end

    if (pPlayer:GetID() == localPlayerID) then
        UI.SetInterfaceMode(InterfaceModeTypes.CITY_MANAGEMENT);
    elseif (localPlayerID == PlayerTypes.OBSERVER
            or localPlayerID == PlayerTypes.NONE
            or pPlayer:GetDiplomacy():HasMet(localPlayerID)) then
        LuaEvents.CQUI_CityviewDisable(); -- Make sure the cityview is disable
    end

    return;
end
``

That _localPlayerID_ variable is never initialized, and I am betting that creates some of this havoc.  There is also code here that is missing where it should return if the City lookup fails.  The branch I created for this issue restores the full OnCityBannerClick replacement function as by the time I had implemented all of the checks in this extension function, it was nearly the size of the function it was extending anyway.

HerpBrownstainz from Steam has been helping out on this, and will test and see if there's any improvement.

**Comment by Infixo** [comment]
> That localPlayerID variable is never initialized, and I am betting that creates some of this havoc.
Good catch!
