### ISSUE TITLE
Sugested Mods for Integration

### ISSUE THREAD

**Issue by Nani-Sore-0** [civfanatics/CQUI_Community-Edition#89]
### Intro
<sup>reading time: 3 min</sup>
After going through all mods on the Civ VI workshop under the UI tag (most are not UI mods), I have found the following mods an objective improvement. I will keep the descriptions short as the screenshots on the Steam workshop do a much better job.
I will list mods and the reasons why, I feel, they should be integrated. Mods appear in order of importance. All these mods I have used in multiple games with CQUI without any issues.
### Alternate Policy Screen ([link](https://steamcommunity.com/sharedfiles/filedetails/?id=1307248778))
If you had to pick one mod from here, make it this one. Gets rid of the clunky card layout and adding more options to sort policies. The “new” category being particularly useful. It gets even better when used in combination with the following mod.
### Better Report Screen ([link](https://steamcommunity.com/sharedfiles/filedetails/?id=1312585482))
The amount of information, and time saved with this mod is insane. Here are some things I used it for: finding the third most productive city, finding a specific apostle, finding idle workers and traders and a lot more. It gets even better when combined with the mod above, because now each policy shows how much effect it will have. Screenshots [here](https://steamuserimages-a.akamaihd.net/ugc/1257016010460690748/3DF6BF557916015A4318B9442ED6689F881478E0/).
### Notification Log + Simplified Combat Reports ([link 1](https://steamcommunity.com/sharedfiles/filedetails/?id=1459493312)) ([link2](https://steamcommunity.com/sharedfiles/filedetails/?id=1459524722))
I nearly went cross eyed with 10 rumors popping up every turn informing me that someone build an aqueduct district. This mod moves it all into a nice and compact panel on the side. Combine with the Simplified Combat Report and it just very nice to look at. The Notification Log mod is the only one that didn’t work out of the box, requiring the Simplified Gossip mod to be enabled, even though it’s integrated into CQUI.

Side note: I feel these mod would be rendered unnecessary by reducing the amount of useless gossip. The only ones that have been useful to me are the wonder and considering war ones.
### Better World Rankings + Global Relations Panel ([link 1](https://steamcommunity.com/sharedfiles/filedetails/?id=2139486665)) ([link2](https://steamcommunity.com/sharedfiles/filedetails/?id=1753346735))
I can live without these mods, but they are useful nevertheless. Their names should be description enough. They are particularly useful for Cultural victories.

Thanks for reading and your work.

**Comment by Infixo** [comment]
@Nani-Sore-0 Right now the philosophy is to reduce or maybe even remove all integrations. Integrations add little to no value but require constant attention and overall increase amount of work on the mod.
We agreed that exceptions could be situations where author(s) no longer maintain the mod.

**Comment by alexeyOnGitHub** [comment]
@Nani-Sore-0  I definitely agree that using the standard game UI is painful and counter-productive. it seems to me that **no one on the gamedev team actually plays the game start to finish**:  
every individual game component works to achieve its locally-stated goal (add unit to queue - works, build a wonder - works, replace a card - works, etc), but the overall user experience is just horrendous. if you **ever played a single game start to finish**, you would see how disjointed and suboptimal the user experience is. 
this is the main impediment for me personally to play the game regularly. 
any Civ player with a 1000+ hours of experience could easily produce (and probably would be just happy to do it, if asked!) a list of potential changes for the UX that would greatly improve user satisfaction, thus making it more re-playable. 

but... I am afraid the UX situation is not likely to be addressed by the game studio in the near future. the existing players (those who have already PAID) do not contribute much to the additional profits the company needs to acquire to be able to survive... I am actually glad the company may be inching towards the monthly/yearly subscription model (as opposed to "buy once, use forever"). as much as some people are wary about this, this may be a way for the company to maintain enough of a profit level to be able to invest into things like UX and everything else. this is a total speculation on my part though, so don't take this to the bank.

anyway, I am glad that some of the existing UI mods address certain shortcomings of the game, making them less painful. 

as far as the mods integration goes - as @Infixo  mentioned, one potential reason for pulling mods into this one would be if the original mod is abandoned. but even then - we could just fork them into our github org and maintain them there.

while bundling multiple plugins into one simplifies their discoverability (no need to search for multiple plugins), the downside is that every time a game patch is released, something can break (that would be a whole other interesting discussion on the value of exposing and maintaining stable APIs, ensuring that external popular mods work, etc). if things do break , the user would need to disable the WHOLE plugin , thus losing access to all the goodies and not just that one piece that is broken.

what I would propose instead is **having some page listing the reviewed, tested and "community-recommended" UI mods, with some compatibility matrix or notes.** 
maybe a README file in this repo, or have a separate REPO just with docs ( to indicate that this is not a part of CQUI, but rather some general information about Civ 6 game).
I would start with a chapter in the README file in this repo to simplify the discoverability of this information for our beloved visitors who this whole thing is created for.

tagging @alimulhuda  and @the-m4a as well

**Comment by alimulhuda** [comment]
I agree with what Infixo and alexeyOnGitHub says. Also to add a bit of past info, we have at times looked over requests where people had conflicts between CQUI and other mods, and made changes where possible to make it so that they are compatible. That will not always be the case but I think we have been looking at those things on a case-by-case basis.

The report screen one (BRS) is one of Infixo's and I believe he mentioned somewhere else that it should just work alongside CQUI. If the other ones have issues working alongside CQUI, then let us know here. No promises but sometimes the fix is easy to do and we can probably try a compatibility fix for those ones.

**Comment by Nani-Sore-0** [comment]
@alexeyOnGitHub I feel like this is always the trade off of semi-complex strategy games aimed at the mainstream market. The UI in Civ VI works well, I feel, for a casual Prince/King player that only plays sometimes or doesn't really "push the game."

I fell like have have misunderstood. When I saw that some mods where integrated I assumed you are looking for more and that the goal was to unify all good UI mods into one mod. Even if you did integrate all the mods above, in a sense that I have one mod and not several, nothing would really change for me as it all works as expected.

> what I would propose instead is having some page listing the reviewed, tested and "community-recommended" UI mods, with some compatibility matrix or notes.

Adding links and and a list showing compatibility, under an optional "add-on" section perhaps, would have the same practical results as integration.

One more thing, change the README to say on the top that this is the updated version. If you google CQUI you end up on the old Azurency repository and it looks identical to this one, at a glance of course.
