### ISSUE TITLE
Screenshots/Graphics for the Workshop post

### ISSUE THREAD

**Issue by the-m4a** [civfanatics/CQUI_Community-Edition#91]
I updated the 512x512 picture - at least changed it to differentiate it from the old version that is no longer updated.
I've seen multiple mods with screenshots showing off various aspects; I would like to add some as well, and would appreciate suggestions/submissions, etc.

Here's the 512x512 graphic, I have not yet checked it into the repo (in the workshop artifacts folder), I'll do that sometime this weekend

![image](https://user-images.githubusercontent.com/8787640/87220143-58848c80-c316-11ea-9589-8fb431b0c645.png)

**Comment by Infixo** [comment]
I am a fan of minimalistic approach. I wouldn’t add the screenshot. Screenshots should be just attached as pictures. This is a logo, 512x512, anything on this screenshot is barely visible.

I like the the idea of those 3 bars from 3 game setups. Plus the name with the year. For me that’s enough.

**Comment by the-m4a** [comment]
I wasn't clear - not a screen shot of the entire screen, but shots of the game that show off some of the elements.  Given what we observed with people going to the old version of the mod and complaining it didn't work, we know a lot of folks don't like to read.  Plus, some nice additions have been made, so showing them off would be good.

For example, like what Sukritact has on his mod:
![image](https://user-images.githubusercontent.com/8787640/87258751-f1242500-c45a-11ea-99c5-45f3b37d26d6.png)

This is one I just did, as an example (this is a snip from the screen, actual was 1200x800).  Same color scheme though I can't find that font from the original logo screen anywhere

**Comment by the-m4a** [comment]
Another one:
![image](https://user-images.githubusercontent.com/8787640/87261126-e755ee00-c469-11ea-91fd-f78d7fad550e.png)

**Comment by Infixo** [comment]
I’ve seen the pics on Steam, nice job.
What is the font you use to add descriptions?

**Comment by alimulhuda** [comment]
I just noticed the update too. Very nice having the picture summary.

Minor typo in the Religion image, it says Religon.

**Comment by the-m4a** [comment]
D'oh, fixed the Religion one.  Working on that too late at night.  I had used "Goudy Old Style", but just realized the in-game fonts are probably packaged with it... and they are, so I'll update with the "official" font
