### ISSUE TITLE
Unlocked citizens indicator is not showing anymore

### ISSUE THREAD

**Issue by wayneb64** [civfanatics/CQUI_Community-Edition#92]
There used to be a little circle that showed up whenever your city had citizens that had not been locked into a tile. I now see the district count icon which I am guessing will go away if the city is at max districts. Was the unlocked citizen removed to make room for this? 

I am always looking for unlocked citizens as the game never seems to quite follow my instructions in filling spots, especially when district spots are involved.

I am running latest version of everything and playing as Maya this game.

**Comment by Infixo** [comment]
District Available is a new indicator.
