### ISSUE TITLE
Improved resource icons are dimmed only after a reload

### ISSUE THREAD

**Issue by angelolocritani** [civfanatics/CQUI_Community-Edition#95]
**Describe the bug**
If I improve a resource, it should be dimmed, but that happens only when I reload the save, not immediately nor next turn.

**To Reproduce**
Improve a resource - it remains "not dimmed" until you reload the save

**Expected behavior**
Resource should became dimmed next turn

**Screenshots**
![1_toBeImproved](https://user-images.githubusercontent.com/67960642/87464991-4e170b00-c614-11ea-9871-ff0e031eba9d.jpg)
before improving
![2_Improved](https://user-images.githubusercontent.com/67960642/87464987-4d7e7480-c614-11ea-88bd-f270f1d5c007.jpg)
Several turns after resource has been improved

![3_reloaded](https://user-images.githubusercontent.com/67960642/87464989-4e170b00-c614-11ea-9a74-011af088a9bc.jpg)
After reloading the save

**General informations**
 - OS: Win
 - Version 1.0.2.39
 - Expansion None

**Comment by the-m4a** [comment]
ok, i think i figured this out, I'll do a pull request tomorrow

**Comment by Infixo** [comment]
Fixed and tested.
