### ISSUE TITLE
Removing some CQUI hotkeys

### ISSUE THREAD

**Issue by alimulhuda** [civfanatics/CQUI_Community-Edition#96]
I would like to remove CQUI handling of some keyboard shortcuts.
These seem to be all the keys that CQUI support and also can be rebound to whatever the user wants in the base game.

Function|Base game key default|CQUI
-|-|-
Next City|]|E (When city selected)
Previous City|[|Q (When city selected)
Next Ready Unit|.|E (When city not selected)
Prev Ready Unit|,|Q (When city not selected)
Pan Map|Arrow Keys|WSAD
Auto Explore|E|Alt + E
Capital City|\ |Home
Air Strike/Ranged Attack|R|S or Alt+S depending on CQUI option

I think CQUI added these since originally the game didn't have hotkeys for some of these functions. For some that had assigned hotkeys the game didn't allow remapping to other keys (I believe panning was hardcoded to the arrow keys).
Since now the base game does have the functionality to remap those functions I am proposing that we remove them from CQUI and let the base game handle them. Any thoughts, objections, concerns? (@alexeyOnGitHub , @the-m4a , @Infixo , and anyone else who runs across this)

**Comment by the-m4a** [comment]
This seems ok with me - assuming the game lets you remap as you indicate. Communicating changes to people subscribed isn't easiest thing to do - I mean they could go to the page but would it be worth it to put a message on the key bindings CQUi menu to say "use the keyboard mappings built into the game" or similar message?
