### ISSUE TITLE
Religious counts not updating unless city is converted.

### ISSUE THREAD

**Issue by wayneb64** [civfanatics/CQUI_Community-Edition#97]
If a priest spreads religion to a city, the counts on the city banner do not reflect what was promised by the mouse over on the spread button. If you save/reload the counts are correct, same for the next turn. If the spread results in a conversion the city does show that, but NOT if the current religion is neutralized. 

I am running latest on Win 10 with both expansions.

**Comment by Infixo** [comment]
When you click the banner, the “subbanner” opens with more or less the same information (e.g. it has a small pie chart). Does it reflect the information properly or is it also out of sync until the next turn?

**Comment by wayneb64** [comment]
Didn't look at the chart but the numbers matched the banner.

**Comment by Infixo** [comment]
This “subbanner” is an original one from vanilla game. Which means the issue is with the vanilla game not updating the banner mid-turn.
